package org.atzberger.mango.jython;

import org.atzberger.mango.table.JDialog_Edit;
import org.atzberger.mango.table.TableData_Pathname;
import org.atzberger.mango.table.TableData_EditorButton;
import org.atzberger.mango.table.TableData_Filename;
import org.atzberger.mango.table.JTable_Properties1_Default;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.table.TableCellEditor;
import org.atzberger.application.selm_builder.SELM_CouplingOperator;
import org.atzberger.mango.table.TableModel_Properties1_Default;

/**
 *
 * Displays preferences and configuration for users.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 *
 */
public class Atz_Jython_JDialog_Preferences extends JDialog_Edit {
  
  JButton jButton_trigger = null;  /* button triggering opening of the dialog */

  Boolean flagChangeValue = false; /* indicates if value should be changed */

  private HashMap jythonPreferenceData = null;

  int paramIndex_pathNameJythonPackage = -1;
  int paramIndex_pathNameJythonModules = -1;
  int paramIndex_pathNameStartupScript = -1;

  int paramIndex_flag1    = -1;
  
  /** Creates new form JDialog_Edit_CouplingOpList */
  public Atz_Jython_JDialog_Preferences(java.awt.Frame parent, boolean modal) {
    super(parent, modal);

    initComponents();
    //modifyComponents();
  }

  public Atz_Jython_JDialog_Preferences(HashMap jythonPreferenceData_in) {
    jythonPreferenceData = jythonPreferenceData_in;

    initComponents();
    modifyComponents();

    setModal(true);  /* must be Modal to handle event processing correctly */

    setDataValue(jythonPreferenceData,"","");
  }

  public Atz_Jython_JDialog_Preferences() {
    initComponents();
    //modifyComponents();
    setModal(true);  /* must be Modal to handle event processing correctly */
  }

  void modifyComponents() {

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Jython_Preferences = new JTable_Properties1_Default();
        jPanel1 = new javax.swing.JPanel();
        jButton_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(Atz_Jython_JDialog_Preferences.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(null);
        setName("Form"); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable_Jython_Preferences.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_Jython_Preferences.setModel(new TableModel_Properties1_Default());
        jTable_Jython_Preferences.setName("jTable_Jython_Preferences"); // NOI18N
        jTable_Jython_Preferences.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable_Jython_Preferences);

        jPanel1.setName("jPanel1"); // NOI18N

        jButton_Close.setText(resourceMap.getString("jButton_Close.text")); // NOI18N
        jButton_Close.setMaximumSize(new java.awt.Dimension(79, 100));
        jButton_Close.setMinimumSize(new java.awt.Dimension(79, 100));
        jButton_Close.setPreferredSize(new java.awt.Dimension(79, 100));
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(377, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed

    int I;

    /* register any partially completed edits as being final */
    TableCellEditor editor = jTable_Jython_Preferences.getCellEditor();
    if (editor != null) {
      editor.stopCellEditing();
    }
    
    /* close the window and fire related events */
    setVisible(false);
    flagChangeValue = true;
    
    newValue = this.jythonPreferenceData;

    this.firePropertyChange(ACTION_DIALOG_DONE, 1, 0);
    
  }//GEN-LAST:event_jButton_CloseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        Atz_Jython_JDialog_Preferences dialog = new Atz_Jython_JDialog_Preferences(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Jython_Preferences;
    // End of variables declaration//GEN-END:variables


  public Object getDataValue() {
    
    //if (flagChangeValue) {
      setJythonPreferencesDataFromTable();
      newValue = jythonPreferenceData;
      return newValue;
    //} else {
//      return oldValue;
//    }

  }

  public void setDataValue(Object dataValue, String dataName, String dataType) {

    SELM_CouplingOperator interaction;
    String name;
    int k, N;
    
    super.setDataValue(dataValue, dataName, dataType);
    
    jythonPreferenceData = (HashMap) jythonPreferenceData;
                    
    /* set up the table to display options */
    setTableFromJythonPreferenceData();
       
  }

  void setJythonPreferencesDataFromTable() {
    Object data;

    if (paramIndex_pathNameJythonPackage!= -1) {
      data = jTable_Jython_Preferences.getModel().getValueAt(paramIndex_pathNameJythonPackage, 1);
      if (TableData_Filename.class.isInstance(data)) {
        TableData_Filename tableData_Filename = (TableData_Filename)data;
        jythonPreferenceData.put("pathNameJythonJAR", tableData_Filename.getFilename());
        String strURL = "jar:file:" + tableData_Filename.getFilename() + "!/";
        jythonPreferenceData.put("jythonJarURL", strURL);
      }
    }

    if (paramIndex_pathNameJythonModules!= -1) {
      data = jTable_Jython_Preferences.getModel().getValueAt(paramIndex_pathNameJythonModules, 1);
      if (TableData_Pathname.class.isInstance(data)) {
        TableData_Pathname tableData_Pathname = (TableData_Pathname)data;
        jythonPreferenceData.put("pathNameJythonModules", tableData_Pathname.pathname);
        
      }
    }

     if (paramIndex_pathNameStartupScript!= -1) {
      data = jTable_Jython_Preferences.getModel().getValueAt(paramIndex_pathNameStartupScript, 1);
      if (TableData_Filename.class.isInstance(data)) {
        TableData_Filename tableData_Pathname = (TableData_Filename)data;
        jythonPreferenceData.put("startupJythonScript", tableData_Pathname.getFilename());
      }
    }

  }

  void setTableFromJythonPreferenceData() {

    TableModel_Properties1_Default tableModel;

    tableModel = (TableModel_Properties1_Default) jTable_Jython_Preferences.getModel();
        
    int i = 0;

    TableData_Filename tableData_FilenameJythonPackage = new TableData_Filename();
    //tableData_Filename.setPreferredEditMode(TableData_PathnameJythonModules.EDIT_MODE_STRING);
    tableData_FilenameJythonPackage.setFilename((String) jythonPreferenceData.get("pathNameJythonJAR"));
    
    tableModel.setValueAt("Jython Package JAR", i, 0, tableModel.NOT_EDITABLE);
    tableModel.setValueAt(tableData_FilenameJythonPackage, i, 1, tableModel.EDITABLE);
    tableModel.setValueAt(new TableData_EditorButton(), i, 2, tableModel.EDITABLE);
    paramIndex_pathNameJythonPackage = i;
    i++;

    TableData_Pathname tableData_PathnameJythonModules = new TableData_Pathname();
    tableData_PathnameJythonModules.setPreferredEditMode(TableData_Pathname.EDIT_MODE_STRING);
    tableData_PathnameJythonModules.pathname = (String) this.jythonPreferenceData.get("pathNameJythonModules");
    
    tableModel.setValueAt("Jython Modules", i, 0, tableModel.NOT_EDITABLE);
    tableModel.setValueAt(tableData_PathnameJythonModules, i, 1, tableModel.EDITABLE);
    tableModel.setValueAt(new TableData_EditorButton(), i, 2, tableModel.EDITABLE);
    paramIndex_pathNameJythonModules = i;
    i++;

    TableData_Filename tableData_FilenameStartupScript = new TableData_Filename();
    //tableData_Filename.setPreferredEditMode(TableData_PathnameJythonModules.EDIT_MODE_STRING);
    tableData_FilenameStartupScript.setFilename((String) jythonPreferenceData.get("startupJythonScript"));

    tableModel.setValueAt("Startup Script", i, 0, tableModel.NOT_EDITABLE);
    tableModel.setValueAt(tableData_FilenameStartupScript, i, 1, tableModel.EDITABLE);
    tableModel.setValueAt(new TableData_EditorButton(), i, 2, tableModel.EDITABLE);
    paramIndex_pathNameStartupScript = i;
    i++;

  }
  
  @Override
  public void setVisible(boolean flag) {
    super.setVisible(flag);

    if (flag == false) {
      //jTable_CouplingOpList.changeSelection(0, 1, false, false);
      jTable_Jython_Preferences.clearSelection();
    }

  }
  
  public boolean wasActivatedToGenerateData() {
    return flagChangeValue;
  }
    
  private String[] makeSubArray(String[] array, int N) {
     
    String[] array_new = new String[N];
    
    System.arraycopy(array, 0, array_new, 0, N);

    return array_new;
  }

}
