package org.atzberger.mango.windowing;

import org.atzberger.application.selm_builder.Atz_Application_Data_Communication;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * Provides undocked window capable of holding panel data.  Also provides a
 * unified graphical interface to re-docking panels.
 *
 * This holder automatically senses when a panel's parent is re-assigned to a
 * dockable container and closes.  This allows for operations directly on the
 * panels to trigger appropriate interface responses without need to know the
 * parent type of a panel.  
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JDialog_WindowPanelHolder extends javax.swing.JDialog {

  boolean flagCurrentParentYet = false;
  JPanel panel_ref = null;

    /**
     * Creates new window panel holder.  Makes this window a child of the parent
     * frame.
     *
     * @param parent Main frame to use to reference for icon and modality
     * @param modal How persistent to make the window 
     */
    public JDialog_WindowPanelHolder(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Creates new window panel holder.  Makes this window a child of the parent
     * frame.
     *
     * @param parent Main frame to use to reference for icon and modality
     * @param modal How persistent to make the window
     * @param panel Child panel to hold within this window
     */
    public JDialog_WindowPanelHolder(java.awt.Frame parent, boolean modal, JPanel panel) {
      this(parent, modal);
      setPanel(panel);
    }

    /**
     * Set the held panel explicitly
     *
     * @param panel
     */
  public void setPanel(JPanel panel) {

    String name = panel.getName();
    if (name == null) {
      name = "";
    }

    this.setPanel(name, panel);

  }

  /**
   * Set the panel and assign it a given name
   * 
   * @param name
   * @param panel
   */
  public void setPanel(String name, JPanel panel) {
    //this.removeAll();
    panel_ref = panel;
    
    this.jPanel_holder.add(name, panel_ref);
    flagCurrentParentYet = false;

    this.setTitle(panel_ref.getName());
    
    panel_ref.addHierarchyListener(new HierarchyListener() {

      public void hierarchyChanged(HierarchyEvent e) {
        panel_hierarchyChanged(e);
      }
    });

  }

  /**
   * Detect any changes in how the panel is docked or otherwise arranged in
   * the graphical user interface.  This allows for Jython and other operations
   * directly on the panel class without knowledge of who owns it.  By detecting
   * these changes in location of the panel we can automatically close the window
   * holder when panel is not longer contained within.
   *
   * @param e Event related data for hierarchy changes
   */
  public void panel_hierarchyChanged(HierarchyEvent e) {

    long flags = e.getChangeFlags(); 

    int   id = e.getID();

    if (e.getChanged() == this.panel_ref) {
            
      if (flagCurrentParentYet == false) {

        if (e.getChangedParent() == this.jPanel_holder) {
          flagCurrentParentYet = true;
        }
        
      } else { /* we are known parent */

        if (e.getChangedParent() != this.jPanel_holder) { /* indicates changed away from us */          
          flagCurrentParentYet = false; /* no longer parent */
          this.closeDownWindow();          
        }
        
      } /* end else */

    }
      
    
    
  }
    
    /**
     * Close the window and free up related resources
     */
    public void closeDownWindow() {
      /* check to see if reference panel was removed, if so then dispose this window */      
        this.setVisible(false);
        this.dispose();      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_holder = new javax.swing.JPanel();
        jPanel_controls = new javax.swing.JPanel();
        jButton_redock_LowerRight = new javax.swing.JButton();
        jButton_redock_LowerLeft = new javax.swing.JButton();
        jButton_redock_UpperRight = new javax.swing.JButton();
        jButton_redock_UpperLeft = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(620, 400));
        setModalExclusionType(null);
        setModalityType(null);
        setName("Form"); // NOI18N

        jPanel_holder.setName("jPanel_holder"); // NOI18N
        jPanel_holder.setLayout(new java.awt.CardLayout());

        jPanel_controls.setName("jPanel_controls"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JDialog_WindowPanelHolder.class);
        jButton_redock_LowerRight.setIcon(resourceMap.getIcon("jButton_redock_LowerRight.icon")); // NOI18N
        jButton_redock_LowerRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_redock_LowerRight.setBorderPainted(false);
        jButton_redock_LowerRight.setContentAreaFilled(false);
        jButton_redock_LowerRight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_redock_LowerRight.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButton_redock_LowerRight.setMinimumSize(new java.awt.Dimension(19, 19));
        jButton_redock_LowerRight.setName("jButton_redock_LowerRight"); // NOI18N
        jButton_redock_LowerRight.setPreferredSize(new java.awt.Dimension(19, 19));
        jButton_redock_LowerRight.setRolloverIcon(resourceMap.getIcon("jButton_redock_LowerRight.rolloverIcon")); // NOI18N
        jButton_redock_LowerRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redock_LowerRightActionPerformed(evt);
            }
        });

        jButton_redock_LowerLeft.setIcon(resourceMap.getIcon("jButton_redock_LowerLeft.icon")); // NOI18N
        jButton_redock_LowerLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_redock_LowerLeft.setBorderPainted(false);
        jButton_redock_LowerLeft.setContentAreaFilled(false);
        jButton_redock_LowerLeft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_redock_LowerLeft.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButton_redock_LowerLeft.setMinimumSize(new java.awt.Dimension(19, 19));
        jButton_redock_LowerLeft.setName("jButton_redock_LowerLeft"); // NOI18N
        jButton_redock_LowerLeft.setPreferredSize(new java.awt.Dimension(19, 19));
        jButton_redock_LowerLeft.setRolloverIcon(resourceMap.getIcon("jButton_redock_LowerLeft.rolloverIcon")); // NOI18N
        jButton_redock_LowerLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redock_LowerLeftActionPerformed(evt);
            }
        });

        jButton_redock_UpperRight.setIcon(resourceMap.getIcon("jButton_redock_UpperRight.icon")); // NOI18N
        jButton_redock_UpperRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_redock_UpperRight.setBorderPainted(false);
        jButton_redock_UpperRight.setContentAreaFilled(false);
        jButton_redock_UpperRight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_redock_UpperRight.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButton_redock_UpperRight.setMinimumSize(new java.awt.Dimension(19, 19));
        jButton_redock_UpperRight.setName("jButton_redock_UpperRight"); // NOI18N
        jButton_redock_UpperRight.setPreferredSize(new java.awt.Dimension(19, 19));
        jButton_redock_UpperRight.setRolloverIcon(resourceMap.getIcon("jButton_redock_UpperRight.rolloverIcon")); // NOI18N
        jButton_redock_UpperRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redock_UpperRightActionPerformed(evt);
            }
        });

        jButton_redock_UpperLeft.setIcon(resourceMap.getIcon("jButton_redock_UpperLeft.icon")); // NOI18N
        jButton_redock_UpperLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_redock_UpperLeft.setBorderPainted(false);
        jButton_redock_UpperLeft.setContentAreaFilled(false);
        jButton_redock_UpperLeft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_redock_UpperLeft.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButton_redock_UpperLeft.setMinimumSize(new java.awt.Dimension(19, 19));
        jButton_redock_UpperLeft.setName("jButton_redock_UpperLeft"); // NOI18N
        jButton_redock_UpperLeft.setPreferredSize(new java.awt.Dimension(19, 19));
        jButton_redock_UpperLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_redock_UpperLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_controlsLayout = new javax.swing.GroupLayout(jPanel_controls);
        jPanel_controls.setLayout(jPanel_controlsLayout);
        jPanel_controlsLayout.setHorizontalGroup(
            jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_controlsLayout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(jButton_redock_UpperLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_redock_LowerLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_redock_UpperRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_redock_LowerRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_controlsLayout.setVerticalGroup(
            jPanel_controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_redock_LowerRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton_redock_UpperRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton_redock_LowerLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton_redock_UpperLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_holder, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_redock_LowerRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redock_LowerRightActionPerformed

      /* dock this window to the preferred location */
      JTabbedPane jTabbedPane = Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.jTabbedPane_Docksite_Windows_LowerRight;
      Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.openInDockableWindowPanel(panel_ref,jTabbedPane);

      /* close and kill this dialog window */
      this.setVisible(false);
      this.dispose();
      
    }//GEN-LAST:event_jButton_redock_LowerRightActionPerformed

    private void jButton_redock_LowerLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redock_LowerLeftActionPerformed

      /* dock this window to the preferred location */
      JTabbedPane jTabbedPane = Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.jTabbedPane_Docksite_Windows_LowerLeft;
      Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.openInDockableWindowPanel(panel_ref,jTabbedPane);

      /* close and kill this dialog window */
      this.setVisible(false);
      this.dispose();

    }//GEN-LAST:event_jButton_redock_LowerLeftActionPerformed

    private void jButton_redock_UpperRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redock_UpperRightActionPerformed

      /* dock this window to the preferred location */
      JTabbedPane jTabbedPane = Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.jTabbedPane_Docksite_Windows_UpperRight;
      Atz_Application_Data_Communication.getApplSharedData().FrameView_Application_Main.openInDockableWindowPanel(panel_ref,jTabbedPane);

      /* close and kill this dialog window */
      this.setVisible(false);
      this.dispose();

    }//GEN-LAST:event_jButton_redock_UpperRightActionPerformed

    private void jButton_redock_UpperLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_redock_UpperLeftActionPerformed

      /* Not allowed at this time */
      
    }//GEN-LAST:event_jButton_redock_UpperLeftActionPerformed

    /**
     * Main allows for this window holder to be run directly for testing purposes.
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_WindowPanelHolder dialog = new JDialog_WindowPanelHolder(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_redock_LowerLeft;
    private javax.swing.JButton jButton_redock_LowerRight;
    private javax.swing.JButton jButton_redock_UpperLeft;
    private javax.swing.JButton jButton_redock_UpperRight;
    private javax.swing.JPanel jPanel_controls;
    private javax.swing.JPanel jPanel_holder;
    // End of variables declaration//GEN-END:variables

}
