package org.atzberger.application.selm_builder;

import org.atzberger.mango.table.TableModel_Properties1_Default;
import org.atzberger.mango.table.JDialog_Edit;
import org.atzberger.mango.table.TableData_Pathname;
import org.atzberger.mango.table.TableData_EditorButton;
import org.atzberger.mango.table.JTable_Properties1_Default;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.table.TableCellEditor;

/**
 *
 * Dialog for input from the user when generating data files.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JDialog_Generate_Simulation_Data_LAMMPS extends JDialog_Edit {
  
  JButton jButton_trigger = null;  /* button triggering opening of the dialog */

  Boolean flagChangeValue = false; /* indicates if value should be changed */

  private HashMap genSimulationData = null;

  int paramIndex_pathName = -1;
  int paramIndex_flag1    = -1;
  
  /** Creates new form JDialog_Edit_CouplingOpList */
  public JDialog_Generate_Simulation_Data_LAMMPS(java.awt.Frame parent, boolean modal) {
    super(parent, modal);

    initComponents();
    //modifyComponents();
  }

  public JDialog_Generate_Simulation_Data_LAMMPS(HashMap genSimulationData_in) {
    genSimulationData = genSimulationData_in;

    initComponents();
    modifyComponents();

    setModal(true);  /* must be Modal to handle event processing correctly */

    setDataValue(genSimulationData,"","");
  }

  public JDialog_Generate_Simulation_Data_LAMMPS() {
    initComponents();
    //modifyComponents();
    setModal(true);  /* must be Modal to handle event processing correctly */
  }

  void modifyComponents() {

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Generate_Simulation_Data = new org.atzberger.mango.table.JTable_Properties1_Default();
        jPanel1 = new javax.swing.JPanel();
        jButton_OK = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JDialog_Generate_Simulation_Data_LAMMPS.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(null);
        setName("Form"); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable_Generate_Simulation_Data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_Generate_Simulation_Data.setModel(new org.atzberger.mango.table.TableModel_Properties1_Default());
        jTable_Generate_Simulation_Data.setName("jTable_Generate_Simulation_Data"); // NOI18N
        jTable_Generate_Simulation_Data.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTable_Generate_Simulation_Data);

        jPanel1.setName("jPanel1"); // NOI18N

        jButton_OK.setText(resourceMap.getString("jButton_OK.text")); // NOI18N
        jButton_OK.setMaximumSize(new java.awt.Dimension(79, 100));
        jButton_OK.setMinimumSize(new java.awt.Dimension(79, 100));
        jButton_OK.setName("jButton_OK"); // NOI18N
        jButton_OK.setPreferredSize(new java.awt.Dimension(79, 100));
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_Close.setText(resourceMap.getString("jButton_Close.text")); // NOI18N
        jButton_Close.setMaximumSize(new java.awt.Dimension(79, 100));
        jButton_Close.setMinimumSize(new java.awt.Dimension(79, 100));
        jButton_Close.setName("jButton_Close"); // NOI18N
        jButton_Close.setPreferredSize(new java.awt.Dimension(79, 100));
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(157, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName(resourceMap.getString("Form.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed

    int I;

    /* register any partially completed edits as being final */
    TableCellEditor editor = jTable_Generate_Simulation_Data.getCellEditor();
    if (editor != null) {
      editor.stopCellEditing();
    }

    /* generate the simulation data */


    /* close the window and fire related events */
    setVisible(false);
    flagChangeValue = true;
    
    newValue = genSimulationData;

    this.firePropertyChange(ACTION_DIALOG_DONE, 1, 0);
    
  }//GEN-LAST:event_jButton_OKActionPerformed

  private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
      this.setVisible(false);

      //flagChangeValue = false;
      //newValue = null;

      newValue = genSimulationData;

      this.firePropertyChange(ACTION_DIALOG_DONE, 1, 0);
  }//GEN-LAST:event_jButton_CloseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        JDialog_Generate_Simulation_Data_LAMMPS dialog = new JDialog_Generate_Simulation_Data_LAMMPS(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Close;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Generate_Simulation_Data;
    // End of variables declaration//GEN-END:variables


  public Object getDataValue() {
    
    //if (flagChangeValue) {
      setGenSimulationDataFromTable();
      newValue = genSimulationData;
      return newValue;
    //} else {
//      return oldValue;
//    }

  }

  public void setDataValue(Object dataValue, String dataName, String dataType) {

    SELM_CouplingOperator interaction;
    String name;
    int k, N;
    
    super.setDataValue(dataValue, dataName, dataType);
    
    genSimulationData = (HashMap) dataValue;
                    
    /* set up the table to display options */
    setTableFromGenSimulationData();
       
  }

  void setGenSimulationDataFromTable() {
    Object data;

    if (paramIndex_pathName!= -1) {
      data = jTable_Generate_Simulation_Data.getModel().getValueAt(paramIndex_pathName, 1);
      if (TableData_Pathname.class.isInstance(data)) {
        TableData_Pathname tableData_Pathname = (TableData_Pathname)data;
        genSimulationData.put("pathName", tableData_Pathname.pathname);
      }
    }

    if (paramIndex_flag1 != -1) {
      data = jTable_Generate_Simulation_Data.getModel().getValueAt(paramIndex_flag1, 1);
      if (Boolean.class.isInstance(data)) {
        Boolean flagValue       = (Boolean)data;
        genSimulationData.put("flag1", new Boolean(flagValue));
      }
    }
    
  }

  void setTableFromGenSimulationData() {

    TableModel_Properties1_Default tableModel_GenSimulationData;

    tableModel_GenSimulationData = (TableModel_Properties1_Default) jTable_Generate_Simulation_Data.getModel();
    
    TableData_Pathname tableData_Pathname = new TableData_Pathname();
    tableData_Pathname.setPreferredEditMode(TableData_Pathname.EDIT_MODE_STRING);
    tableData_Pathname.pathname = (String) genSimulationData.get("pathName");

    int i = 0;
    tableModel_GenSimulationData.setValueAt("File path", i, 0, tableModel_GenSimulationData.NOT_EDITABLE);
    tableModel_GenSimulationData.setValueAt(tableData_Pathname, i, 1, tableModel_GenSimulationData.EDITABLE);
    tableModel_GenSimulationData.setValueAt(new TableData_EditorButton(), i, 2, tableModel_GenSimulationData.EDITABLE);
    paramIndex_pathName = i;
    i++;

    Boolean flag1Data = new Boolean(false);
    flag1Data         = (Boolean) genSimulationData.get("flag1");
    tableModel_GenSimulationData.setValueAt("Include comments", i, 0, tableModel_GenSimulationData.NOT_EDITABLE);
    tableModel_GenSimulationData.setValueAt(flag1Data, i, 1, tableModel_GenSimulationData.EDITABLE);
    tableModel_GenSimulationData.setValueAt(new TableData_EditorButton(), i, 2, tableModel_GenSimulationData.EDITABLE);
    paramIndex_flag1 = i;
    i++;
    
  }
  
  @Override
  public void setVisible(boolean flag) {
    super.setVisible(flag);

    if (flag == false) {
      //jTable_CouplingOpList.changeSelection(0, 1, false, false);
      jTable_Generate_Simulation_Data.clearSelection();
    }

  }
  
  public boolean wasActivatedToGenerateData() {
    return flagChangeValue;
  }
    
  private String[] makeSubArray(String[] array, int N) {
     
    String[] array_new = new String[N];
    
    System.arraycopy(array, 0, array_new, 0, N);

    return array_new;
  }

}
