package org.atzberger.application.selm_builder;

import org.atzberger.mango.table.JDialog_Edit;
import org.atzberger.mango.table.JTable_Properties1_Default;
import javax.swing.JButton;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;

/**
 *
 * Editor for the list of named data entries.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JDialog_Edit_InteractionList extends JDialog_Edit implements TableModelListener {

  //protected static final String ACTION_BUTTON_OK = "ACTION_BUTTON_OK";
  //protected static final String ACTION_BUTTON_CANCEL = "ACTION_BUTTON_CANCEL";
  JButton jButton_trigger = null;  /* button triggering opening of the dialog */

  Boolean flagChangeValue = false; /* indicates if value should be changed */
  
  TableData_InteractionList tableData_InteractionList = null;

  /** Creates new form JDialog_Edit_InteractionList */
  public JDialog_Edit_InteractionList(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    //modifyComponents();
  }

  public JDialog_Edit_InteractionList() {    
    initComponents();
    //modifyComponents();
    setModal(true);  /* must be Modal to handle event processing correctly */
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable_CouplingOpList = new JTable_Properties1_Default();
    jPanel1 = new javax.swing.JPanel();
    jButton_OK = new javax.swing.JButton();
    jButton_Cancel = new javax.swing.JButton();
    jButton_Remove = new javax.swing.JButton();
    jComboBox_Add_Interaction = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Form"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jTable_CouplingOpList.setModel(new TableModel_InteractionList());
    jTable_CouplingOpList.getModel().addTableModelListener(this);
    jTable_CouplingOpList.setName("jTable_CouplingOpList"); // NOI18N
    jScrollPane1.setViewportView(jTable_CouplingOpList);

    jPanel1.setName("jPanel1"); // NOI18N

    jButton_OK.setMaximumSize(new java.awt.Dimension(79, 100));
    jButton_OK.setMinimumSize(new java.awt.Dimension(79, 100));
    jButton_OK.setName("jButton_OK"); // NOI18N
    jButton_OK.setPreferredSize(new java.awt.Dimension(79, 100));
    jButton_OK.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_OKActionPerformed(evt);
      }
    });

    jButton_Cancel.setMaximumSize(new java.awt.Dimension(79, 100));
    jButton_Cancel.setMinimumSize(new java.awt.Dimension(79, 100));
    jButton_Cancel.setName("jButton_Cancel"); // NOI18N
    jButton_Cancel.setPreferredSize(new java.awt.Dimension(79, 100));
    jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_CancelActionPerformed(evt);
      }
    });

    jButton_Remove.setMaximumSize(new java.awt.Dimension(79, 100));
    jButton_Remove.setMinimumSize(new java.awt.Dimension(79, 100));
    jButton_Remove.setName("jButton_Remove"); // NOI18N
    jButton_Remove.setPreferredSize(new java.awt.Dimension(79, 100));
    jButton_Remove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_RemoveActionPerformed(evt);
      }
    });

    jComboBox_Add_Interaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Interaction", "PAIRS_HARMONIC", "PAIRS_TABLE" }));
    jComboBox_Add_Interaction.setName("jComboBox_Add_Interaction"); // NOI18N
    jComboBox_Add_Interaction.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox_Add_InteractionActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(jButton_OK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton_Cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(52, 52, 52)
        .addComponent(jComboBox_Add_Interaction, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(32, 32, 32)
        .addComponent(jButton_Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(12, 12, 12))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBox_Add_Interaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(29, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
            .addGap(12, 12, 12))
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed

    /* register any partially completed edits as being final */
    TableCellEditor editor = jTable_CouplingOpList.getCellEditor();
    if (editor != null) {
      editor.stopCellEditing();
    }

    /* close the window and fire related events */

    this.setVisible(false);
    flagChangeValue = true;
    newValue = tableData_InteractionList;

    this.firePropertyChange(ACTION_DIALOG_DONE, 1, 0);
    
  }//GEN-LAST:event_jButton_OKActionPerformed

  private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
      this.setVisible(false);

      flagChangeValue = false;
      newValue = null;

      this.firePropertyChange(ACTION_DIALOG_DONE, 1, 0);
  }//GEN-LAST:event_jButton_CancelActionPerformed

  private void jButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveActionPerformed

    /* Determine the selected rows and remove entries from the interactionList */
    int selectedRows[] = jTable_CouplingOpList.getSelectedRows();

    if (selectedRows.length > 0) {
      int k;
      int N = tableData_InteractionList.interactionList.length;
      int mask[] = new int[N];
      int I;
      int newN;
      SELM_Interaction[] interactionList_new;

      for (k = 0; k < N; k++) {
        mask[k] = 1; /* indicates to keep this entry */
      }

      newN = N;
      for (k = 0; k < selectedRows.length; k++) {
        I = selectedRows[k];
        mask[I] = 0; /* indicates this is row to delete */
        newN--;
      }

      interactionList_new = new SELM_Interaction[newN];
      I = 0;
      for (k = 0; k < N; k++) {
        if (mask[k] == 1) {
          interactionList_new[I] = tableData_InteractionList.interactionList[k];
          I++;
        }
      }

      tableData_InteractionList.interactionList = interactionList_new;

      setDataValue(tableData_InteractionList, "Name", "Type");

      /* set the selected row */
      if (selectedRows[0] < newN) {
        jTable_CouplingOpList.setRowSelectionInterval(selectedRows[0], selectedRows[0]);
      } else if (newN > 0) {
        jTable_CouplingOpList.setRowSelectionInterval(newN - 1, newN - 1);
      }

    }
                    
  }//GEN-LAST:event_jButton_RemoveActionPerformed

  private void jComboBox_Add_InteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Add_InteractionActionPerformed

    String selectedType = (String) jComboBox_Add_Interaction.getSelectedItem();

    SELM_Interaction   newInteraction = null;
    SELM_Interaction[] interactionList_new;
   
    if (selectedType.equals("PAIRS_HARMONIC")) {

      SELM_Interaction_PAIRS_HARMONIC newInteraction_PAIRS_HARMONIC
        = new SELM_Interaction_PAIRS_HARMONIC();

      newInteraction_PAIRS_HARMONIC.InteractionName    = "Name Here";
      
      newInteraction = newInteraction_PAIRS_HARMONIC;
    }

    if (selectedType.equals("PAIRS_TABLE")) {

      SELM_Interaction_PAIRS_TABLE newInteraction_PAIRS_TABLE
        = new SELM_Interaction_PAIRS_TABLE();

      newInteraction_PAIRS_TABLE.InteractionName    = "Name Here";

      newInteraction = newInteraction_PAIRS_TABLE;
    }

    if (newInteraction != null) {
      /* add the interaction to the list */
      int N = tableData_InteractionList.interactionList.length;
      interactionList_new = new SELM_Interaction[N + 1];
      System.arraycopy(tableData_InteractionList.interactionList, 0,
              interactionList_new, 0, N);

      interactionList_new[N] = newInteraction;

      tableData_InteractionList.interactionList = interactionList_new;

      setDataValue(tableData_InteractionList,"Name","Type");
    }

    /* reset the selection to zero */
    jComboBox_Add_Interaction.setSelectedIndex(0);

  }//GEN-LAST:event_jComboBox_Add_InteractionActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        JDialog_Edit_InteractionList dialog = new JDialog_Edit_InteractionList(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_Cancel;
  private javax.swing.JButton jButton_OK;
  private javax.swing.JButton jButton_Remove;
  private javax.swing.JComboBox jComboBox_Add_Interaction;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable_CouplingOpList;
  // End of variables declaration//GEN-END:variables


  public Object getDataValue() {

    //newValue = (Object) jTextField_SimpleArray_Value.getText();

    if (flagChangeValue) {
      return newValue;
    } else {
      return oldValue;
    }

  }

  public void setDataValue(Object dataValue, String dataName, String dataType) {

    SELM_Interaction interaction;
    String name;
    int k, N;

    TableModel_InteractionList tableModel_InteractionList;

    super.setDataValue(dataValue, dataName, dataType);

    tableModel_InteractionList = (TableModel_InteractionList) jTable_CouplingOpList.getModel();

    tableData_InteractionList = (TableData_InteractionList) dataValue;

    /* setup the table values */
    N = tableData_InteractionList.interactionList.length;
    for (k = 0; k < N; k++) {
      interaction = tableData_InteractionList.interactionList[k];
      
      tableModel_InteractionList.setValueAt(interaction.InteractionName, k, 0, tableModel_InteractionList.EDITABLE);
      tableModel_InteractionList.setValueAt(interaction.InteractionTypeStr, k, 1, tableModel_InteractionList.NOT_EDITABLE);

    }

    tableModel_InteractionList.maxRowUsed = N - 1;

    tableModel_InteractionList.fireTableDataChanged();

    
  }

  public void tableChanged(TableModelEvent e) {

    int row    = e.getFirstRow();
    int column = e.getColumn();

    SELM_Interaction interaction;

    TableModel model = (TableModel) e.getSource();

    Object data       = model.getValueAt(row, column); /* not column -1 since not selectable */
       
    if ( (data != null) && (e.getType() == e.UPDATE) && (column == 0) ) {            
      /* update all the interaction data */      
      interaction                                    = tableData_InteractionList.interactionList[row];
      interaction.InteractionName                    = (String) model.getValueAt(row, 0);
      //tableData_InteractionList.interactionList[row] = interaction;
    }

  }




  @Override
  public void setVisible(boolean flag) {
    super.setVisible(flag);

    if (flag == false) {
      //jTable_InteractionList.changeSelection(0, 1, false, false);
      jTable_CouplingOpList.clearSelection();
    }

  }
}
