package org.atzberger.application.selm_builder;

import org.atzberger.mango.table.JTable_Properties1_Default;
import org.atzberger.mango.atz3d.Atz3D_Model;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel helper for dealing with the table.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Helper_Integrator_GenericTable extends JPanel_Integrator {

  public JPanel_Helper_Integrator_GenericTable() {
    this(null); /* call constructor with null as model */
  }
          
  public JPanel_Helper_Integrator_GenericTable(TableModel_Integrator model) {
    initComponents();
    modifyComponents();

    if (model == null) {
      setTableModel(new org.atzberger.application.selm_builder.TableModel_Integrator()); /* default model to use */
    } else {
      setTableModel(model);
    }
           
  }

  public void jTable_Integrator_tableChanged(TableModelEvent e)  {
    //System.out.println("jTable_Integrator changed event" + e);

    fireIntegratorChanged();

  }

  
  public void fireIntegratorChanged() {

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_Integrator_DATA", 0, 1);
    }

  }

  public void setTableModel(TableModel_Integrator model) {

    /* add listener to the jTable for any changes there */
    jTable.setModel(model);

    model.addTableModelListener(new TableModelListener() {
      public void tableChanged(TableModelEvent e)  {
        jTable_Integrator_tableChanged(e);
      }
    });

  }

  
  @Override
  public void setData(SELM_Integrator Integrator) {

    TableModel_Integrator model = (TableModel_Integrator) jTable.getModel();

    /* perform the generic set */
    model.setFromIntegratorData(Integrator);

  }

  @Override
  public SELM_Integrator getData() {

    SELM_Integrator Integrator;

    TableModel_Integrator model = (TableModel_Integrator) jTable.getModel();
    
    /* perform the generic get */
    Integrator = model.getIntegratorDataFromModel();

    return Integrator;
    
  }


  void modifyComponents() {
       
  }

  public JTable getTable() {
    return jTable;
  }

  public JScrollPane getScrollPane() {
    return jScrollPane;
  }

  public JPanel getPanelTableHolder() {
    return jPanel_tableHolder;
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_tableHolder = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jTable = new JTable_Properties1_Default();

        setName("JPANEL_HELPER_GENERIC (use setName() to change this)"); // NOI18N

        jPanel_tableHolder.setName("jPanel_tableHolder"); // NOI18N

        jScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane.setName("jScrollPane"); // NOI18N

        jTable.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jTable.setName("jTable"); // NOI18N
        jTable.setRowSelectionAllowed(false);
        jScrollPane.setViewportView(jTable);

        javax.swing.GroupLayout jPanel_tableHolderLayout = new javax.swing.GroupLayout(jPanel_tableHolder);
        jPanel_tableHolder.setLayout(jPanel_tableHolderLayout);
        jPanel_tableHolderLayout.setHorizontalGroup(
            jPanel_tableHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tableHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_tableHolderLayout.setVerticalGroup(
            jPanel_tableHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tableHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_tableHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_tableHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
      
  public String getRenderTag() {
    return atz3D_RENDER_TAG_INTEGRATOR_ANNOTATION;  /* indicate this is annotation */
  }

  public void renderToModel3D(Atz3D_Model model3D) {
    
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel jPanel_tableHolder;
    protected javax.swing.JScrollPane jScrollPane;
    protected javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

}
