package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel;
import org.atzberger.mango.atz3d.JPanel_Model_View_Composite;
import org.atzberger.mango.atz3d.Atz3D_Element;
import org.atzberger.mango.atz3d.Atz3D_Element_Points_DataClosest;
import org.atzberger.mango.atz3d.Atz3D_Camera;
import org.atzberger.mango.atz3d.Atz3D_Model;
import org.atzberger.mango.atz3d.Atz3D_Element_Points;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Interaction_LAMMPS_SPECIAL_BONDS extends JPanel_Interaction implements SELM_InteractionRenderView {

  public application_SharedData applSharedData = null;
     
  public JPanel_Interaction_LAMMPS_SPECIAL_BONDS(application_SharedData applSharedData_in) {
    
    applSharedData = applSharedData_in;
    initComponents();
    modifyComponents();

    /* add listener to the jTable_Lagrangian for any changes there */
    jTable_Interaction.getModel().addTableModelListener(new TableModelListener() {
      public void tableChanged(TableModelEvent e)  {
        jTable_Interaction_tableChanged(e);
      }
    });

    /* setup method for making objects of the target type */
    atz_Object_Factory = new Atz_Object_Factory_Generic(this.getClass().getPackage().getName(),
                                                                  "SELM_Interaction",
                                                                  this.getName());
    
  }

  public void jTable_Interaction_tableChanged(TableModelEvent e)  {
    //System.out.println("jTable_Interaction changed event" + e);

    fireInteractionChanged();

  }

  
  public void fireInteractionChanged() {

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_INTERACTION_DATA", 0, 1);
    }

  }

  /** Creates new form JPanel_Interaction_ControlPts_BASIC1 */
  //public JPanel_Interaction_LAMMPS_SPECIAL_BONDS() {
  //  initComponents();
  //  modifyComponents();
 // }

  @Override
  public void setData(SELM_Interaction interaction) {

    //SELM_Lagrangian lagrangian_old = ((TableModel_Lagrangian_LAMMPS_ATOM_angle_style)(jTable_Lagrangian.getModel())).getLagrangianDataFromModel();

    ((TableModel_Interaction_LAMMPS_SPECIAL_BONDS)(jTable_Interaction.getModel())).setFromInteractionData(interaction);

    //if ((lagrangian_old == null) || (lagrangian_old.LagrangianName.equals(lagrangian.LagrangianName) == false) ) {
    //if (interfaceModeStr.equals(interfaceMode_MOVE_POINTS) == false) {
      /* reset the selection */
    //  resetControlPtsSelectedList();
    //}

  }

  @Override
  public SELM_Interaction getData() {
    SELM_Interaction interaction;

    interaction = ((TableModel_Interaction_LAMMPS_SPECIAL_BONDS)(jTable_Interaction.getModel())).getInteractionDataFromModel();

    return interaction;
  }


  void modifyComponents() {


        
  }


  public void renderToModel3D(Atz3D_Model model3D) {

   /* nothing to do */

  }

  public String getRenderTag() {
    return atz3D_RENDER_TAG_INTERACTION_ANNOTATION;  /* indicate this is annotation */
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane_Interaction = new javax.swing.JScrollPane();
    jTable_Interaction = new org.atzberger.application.selm_builder.JTable_Interaction_LAMMPS_SPECIAL_BONDS();

    setName("LAMMPS_SPECIAL_BONDS"); // NOI18N

    jScrollPane_Interaction.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jScrollPane_Interaction.setName("jScrollPane_Interaction"); // NOI18N

    jTable_Interaction.setBorder(javax.swing.BorderFactory.createLineBorder(null));
    jTable_Interaction.setModel(new org.atzberger.application.selm_builder.TableModel_Interaction_LAMMPS_SPECIAL_BONDS(null, applSharedData.atz_UnitsRef));
    jTable_Interaction.setName("jTable_Interaction"); // NOI18N
    jTable_Interaction.setRowSelectionAllowed(false);
    jScrollPane_Interaction.setViewportView(jTable_Interaction);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane_Interaction, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane_Interaction, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane_Interaction;
  private javax.swing.JTable jTable_Interaction;
  // End of variables declaration//GEN-END:variables

}
