package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel;
import java.awt.Component;
import java.awt.event.MouseListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;


/**
 *
 * Panel for editing the this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Editor_Interaction extends javax.swing.JPanel {

    application_SharedData applSharedData = null;

    private JPanel_Model_View_RenderPanel jPanel_Render_ControlPts;
    
    private MouseListener jToggleButton_AddingPairs_MouseListener = null;
    private MouseListener jToggleButton_RemovingPairs_MouseListener = null;

    private boolean jComboBox_Interaction_flagRebuildingList = false;

    private TableModel[] jTable_Interaction_ModelList; /* used for switchable table data */

    private SELM_InteractionRenderView[] interactionRenderViewList;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Interaction() {
      initComponents();
      //updateLists();

    }

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Interaction(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
      updateLists();

      /* add listener to the jTable_mainData for any changes there */
      applSharedData.jTable_MainData.getModel().addTableModelListener(new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_MainData_tableChanged(e);
        }
      });
    
    }
    
    void jTable_MainData_tableChanged(TableModelEvent e)  {
      updateLists(); /* update the comboBox and data on change */
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_Interaction = new javax.swing.JComboBox();
        jButton_InteractionList_Modify = new javax.swing.JButton();
        jLabel_Interaction = new javax.swing.JLabel();
        jPanel_InteractionData = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("Interaction Editor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jComboBox_Interaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Interaction.setName("jComboBox_Interaction"); // NOI18N
        jComboBox_Interaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_InteractionActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Editor_Interaction.class);
        jButton_InteractionList_Modify.setText(resourceMap.getString("jButton_InteractionList_Modify.text")); // NOI18N
        jButton_InteractionList_Modify.setName("jButton_InteractionList_Modify"); // NOI18N
        jButton_InteractionList_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InteractionList_ModifyActionPerformed(evt);
            }
        });

        jLabel_Interaction.setText(resourceMap.getString("jLabel_Interaction.text")); // NOI18N
        jLabel_Interaction.setName("jLabel_Interaction"); // NOI18N

        jPanel_InteractionData.setName("jPanel_InteractionData"); // NOI18N
        jPanel_InteractionData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel_InteractionDataPropertyChange(evt);
            }
        });
        jPanel_InteractionData.setLayout(new javax.swing.BoxLayout(jPanel_InteractionData, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Interaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Interaction, 0, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_InteractionList_Modify)
                .addContainerGap())
            .addComponent(jPanel_InteractionData, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Interaction)
                    .addComponent(jComboBox_Interaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_InteractionList_Modify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_InteractionData, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  public void updateLists() {

    String oldSelectedName = (String) jComboBox_Interaction.getSelectedItem();
    
    /* setup the model for the interaction data */
    //jTable_Interaction_build_all_table_Models();

    //if ((jTable_Interaction_ModelList != null) && (jTable_Interaction_ModelList.length > 0)) {
    //  int entryI = jComboBox_InteractionList.getSelectedIndex();
     // if (entryI >= 0) {
     //   jTable_Interaction_CONTROL_PTS.setModel(jTable_Interaction_ModelList[entryI]);
     // }
    //}

    /* update the combo box to reflect all interactions */
    jComboBox_Interaction_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_Interaction_tryToSetSelectionByName(oldSelectedName);

  }

    private void jButton_InteractionList_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InteractionList_ModifyActionPerformed

      /* tell the main application code to select the panel with Lagrangian DOF */
      Component[] componentList = this.applSharedData.jPanel_Tabbed_Main.getComponents();

      int selectIndex = -1;

      for (int k = 0; k < componentList.length; k++) {
        if (componentList[k].getName().equals("jPanel_Interactions")) {
          selectIndex = k;
        }
      }

      if (selectIndex != -1) {
         this.applSharedData.jPanel_Tabbed_Main.setSelectedIndex(selectIndex);
      }

//
//
//      JDialog_Edit_InteractionList dialog;
//
//      /* trigger opening of J_Edit_InteractionList dialog */
//      //Set up the dialog that the button brings up.
//      dialog = new JDialog_Edit_InteractionList();
//
//      dialog.setAlwaysOnTop(true);
//
//      /* == Get the interaction list from the main table */
//      TableModel_MainData model
//        = (TableModel_MainData) applSharedData.jTable_MainData.getModel();
//
//      int col = 1;
//      TableData_InteractionList tableData_InteractionList
//        = (TableData_InteractionList) model.getValueAt(model.paramIndex_InteractionList, col);
//
//      dialog.setDataValue(tableData_InteractionList, model.paramName_InteractionList, TableData_InteractionList.class.toString());
//
//      //dialog.addPropertyChangeListener(this);
//
//      /* setup the responses to the dialog */
//      dialog.addWindowListener(new WindowAdapter() {
//        public void windowClosing(WindowEvent we) {
//          JDialog_Edit_InteractionList dialog = (JDialog_Edit_InteractionList) we.getSource();
//          dialog.firePropertyChange(dialog.ACTION_DIALOG_DONE, 1, 0);
//        }
//      });
//
//      dialog.addPropertyChangeListener(new PropertyChangeListener() {
//
//        public void propertyChange(PropertyChangeEvent e) {
//
//          boolean DEBUG = true;
//          String prop = e.getPropertyName();
//          String code_str = this.getClass().getName();
//          TableData_InteractionList dataValue;
//
//          JDialog_Edit_InteractionList dialog = (JDialog_Edit_InteractionList) e.getSource();
//
//          if (prop.equals(dialog.ACTION_DIALOG_DONE)) {
//            dataValue = (TableData_InteractionList) dialog.getDataValue();
//
//            TableModel_MainData model
//                    = (TableModel_MainData) applSharedData.jTable_MainData.getModel();
//
//            /* update the interactionList data structure */
//            dialog.setVisible(false);
//
//            dataValue = (TableData_InteractionList) dialog.getDataValue();
//
//            /* change the data in the table */
//            model.setEntryByName(model.paramName_InteractionList, dataValue);
//
//            /* rebuild the combo list to reflect changes made */
//            jComboBox_Interaction_rebuild_list();
//
//          } /* ACTION_DIALOG_DONE */
//
//        } /* end event from dialog */
//      });
//
//      /* show the newly created dialog window */
//      dialog.setVisible(true);
    }//GEN-LAST:event_jButton_InteractionList_ModifyActionPerformed

    private void jComboBox_InteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_InteractionActionPerformed

      int entryI  = jComboBox_Interaction.getSelectedIndex();

      /* do not respond if we are only rebuilding the list */
      if (jComboBox_Interaction_flagRebuildingList == false) {

        /* == Change the panel and data to edit selected Interaction DOF */

        /* -- get the Interaction DOF data */
        SELM_Interaction[] interactionList = applSharedData.jTable_MainData.getInteractionList();
        SELM_Interaction interaction       = interactionList[entryI];

        setInteractionData(interaction);
                
        /* interaction editor : change the model displayed in the table  */
        //if ((jTable_Interaction_ModelList != null) && (entryI >=0) && (entryI < jTable_Interaction_ModelList.length))
        //  jTable_Interaction_CONTROL_PTS.setModel(jTable_Interaction_ModelList[entryI]);

      }
      
    }//GEN-LAST:event_jComboBox_InteractionActionPerformed

    public void setInteractionData(SELM_Interaction interaction) {

      /* -- determine the appropriate panel type to use */
      int N;
      jPanel_Interaction = null;
      N = applSharedData.jPanel_Interaction_list.length;
      jPanel_Interaction_index = -1;
      for (int k = 0; k < N; k++) {

        if (applSharedData.jPanel_Interaction_list[k].getName().equals(interaction.InteractionTypeStr)) {
          jPanel_Interaction = (JPanel_Interaction) applSharedData.jPanel_Interaction_list[k];
          jPanel_Interaction_index = k;
        }
        
      }

      /* -- setup the panel data based on SELM_Interaction data structure */
      jPanel_Interaction.setData(interaction);

      /* -- set the panel to display in correct location */
      jPanel_InteractionData.removeAll();
      jPanel_InteractionData.add(jPanel_Interaction);
      jPanel_InteractionData.validate();
      jPanel_InteractionData.repaint();

    }

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      
    }//GEN-LAST:event_formPropertyChange

    private void jPanel_InteractionDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel_InteractionDataPropertyChange
      //System.out.println("JPanel_InteractionData Property Change triggered: " + evt.getPropertyName());

      if (jPanel_Interaction != null) {
        SELM_Interaction interaction = jPanel_Interaction.getData();

        SELM_Interaction[] interactionList = applSharedData.jTable_MainData.getInteractionList();

        //interactionList[jPanel_Interaction_index] = interaction;

        applSharedData.jTable_MainData.setInteractionList(interactionList);
      }
      
    }//GEN-LAST:event_jPanel_InteractionDataPropertyChange

    private void jComboBox_Interaction_rebuild_list() {

    SELM_Interaction[] interactionList;

    /* == Get the interaction list from the ControlPts_BASIC1 table */
    interactionList = ((JTable_MainData)applSharedData.jTable_MainData).getInteractionList();

    if (interactionList != null) {

      /* == Rebuild the list of interactions in the combo box */
      jComboBox_Interaction_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_Interaction.getSelectedItem(); /* save for later */
      jComboBox_Interaction.removeAllItems();
      int N = interactionList.length;
      for (int k = 0; k < N; k++) {
        jComboBox_Interaction.addItem(interactionList[k].InteractionName);
      }
      if (jComboBox_Interaction.getItemCount() > 0) {
        jComboBox_Interaction_tryToSetSelectionByName(oldSelectedName);
      } else { /* no items in list so set to panel to NULL */
        setInteractionPanelToNULL();
      }
      jComboBox_Interaction_flagRebuildingList = false;

    } else {/* end check interactionList != null */
      setInteractionPanelToNULL();
    }

  }

  public void setInteractionPanelToNULL() {
    this.setInteractionData(new SELM_Interaction_NULL());
  }


    
  void jComboBox_Interaction_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_Interaction.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_Interaction.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_Interaction.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_Interaction.setSelectedIndex(selectedIndex);
    }

  }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_InteractionList_Modify;
    private javax.swing.JComboBox jComboBox_Interaction;
    private javax.swing.JLabel jLabel_Interaction;
    private javax.swing.JPanel jPanel_InteractionData;
    // End of variables declaration//GEN-END:variables

  private JPanel_Interaction jPanel_Interaction = null;
  private int jPanel_Interaction_index = -1;

}
