package org.atzberger.application.selm_builder;

/**
 *
 * Panel for editing the this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Eulerian_UNIFORM1_FFTW3 extends JPanel_Eulerian {

  application_SharedData applSharedData;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Eulerian_UNIFORM1_FFTW3(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3 = new javax.swing.JScrollPane();
        jTable_Eulerian_SHEAR_UNIFORM1_FFTW3 = new org.atzberger.mango.table.JTable_Properties1_Default(new org.atzberger.application.selm_builder.TableModel_Properties1_Test1());

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("UNIFORM1_FFTW3"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));

        jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3.setName("jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Eulerian_UNIFORM1_FFTW3.class);
        jTable_Eulerian_SHEAR_UNIFORM1_FFTW3.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jTable_Eulerian_SHEAR_UNIFORM1_FFTW3.border.lineColor"))); // NOI18N
        jTable_Eulerian_SHEAR_UNIFORM1_FFTW3.setModel(new org.atzberger.application.selm_builder.TableModel_Eulerian_SHEAR_UNIFORM1_FFTW3_old(applSharedData));
        jTable_Eulerian_SHEAR_UNIFORM1_FFTW3.setName("jTable_Eulerian_SHEAR_UNIFORM1_FFTW3"); // NOI18N
        jTable_Eulerian_SHEAR_UNIFORM1_FFTW3.setRowSelectionAllowed(false);
        jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3.setViewportView(jTable_Eulerian_SHEAR_UNIFORM1_FFTW3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane_Eulerian_SHEAR_UNIFORM1_FFTW3;
    private javax.swing.JTable jTable_Eulerian_SHEAR_UNIFORM1_FFTW3;
    // End of variables declaration//GEN-END:variables


  public void turnOffActionListenerForEdits() {

  }

  public void turnOnActionListenerForEdits() {

  }

}
