package org.atzberger.application.selm_builder;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.atzberger.mango.table.JTable_Properties1_Default;

/**
 *
 * Panel for editing attributes of a specific data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1 extends JPanel_CouplingOperator {

  public application_SharedData applSharedData = null;

  protected boolean jComboBox_Lagrangian_flagRebuildingList = false;
  protected boolean jComboBox_Eulerian_flagRebuildingList   = false;

  protected String  selectedLagrangian = null;
  protected String  selectedEulerian   = null;

  static public int FLAG_MODE_NULL   = 0;
  static public int FLAG_MODE_NONE   = 1;
  static public int FLAG_MODE_ADD    = 2;
  static public int FLAG_MODE_REMOVE = 3;

  protected int flagMode = FLAG_MODE_NONE;

  public JPanel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1(application_SharedData applSharedData_in) {

    applSharedData = applSharedData_in;
    
    initComponents();

    modifyComponents();

    jToggleButton_Add.setSelected(true);
    flagMode = FLAG_MODE_ADD;

    updateLists();

    /* add listener to the jTable_mainData for any changes there */
    applSharedData.jTable_MainData.getModel().addTableModelListener(new TableModelListener() {

      public void tableChanged(TableModelEvent e) {
        jTable_MainData_tableChanged(e);
      }
    });

  }

  void jTable_MainData_tableChanged(TableModelEvent e)  {
    updateLists(); /* update the comboBox and data on change */
  }

  /** Creates new form JPanel_Lagrangian_ControlPts_BASIC1 */
  public JPanel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1() {
    initComponents();

    modifyComponents();

    updateLists();

  }

  private void modifyComponents() {

    /* add listener to the jTable_Lagrangian for any changes there */
    jTable_CouplingOp_TABLE1.getModel().addTableModelListener(new TableModelListener() {

      public void tableChanged(TableModelEvent e) {
        jTable_CouplingOp_tableChanged(e);
      }
    });

  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup_AddRemove = new javax.swing.ButtonGroup();
    jScrollPane_Lagrangian_ControlPts_BASIC1 = new javax.swing.JScrollPane();
    jTable_CouplingOp_TABLE1 = new JTable_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1();
    jComboBox_Lagrangian_DOF = new javax.swing.JComboBox();
    jComboBox_Eulerian_DOF = new javax.swing.JComboBox();
    jToggleButton_Add = new javax.swing.JToggleButton();
    jToggleButton_Remove = new javax.swing.JToggleButton();

    setName("LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1"); // NOI18N
    setPreferredSize(new java.awt.Dimension(644, 400));

    jScrollPane_Lagrangian_ControlPts_BASIC1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jScrollPane_Lagrangian_ControlPts_BASIC1.setName("jScrollPane_Lagrangian_ControlPts_BASIC1"); // NOI18N

    jTable_CouplingOp_TABLE1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
    jTable_CouplingOp_TABLE1.setModel(new org.atzberger.application.selm_builder.TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1());
    jTable_CouplingOp_TABLE1.setName("jTable_CouplingOp_TABLE1"); // NOI18N
    jTable_CouplingOp_TABLE1.setRowSelectionAllowed(false);
    jScrollPane_Lagrangian_ControlPts_BASIC1.setViewportView(jTable_CouplingOp_TABLE1);

    jComboBox_Lagrangian_DOF.setMaximumRowCount(1000);
    jComboBox_Lagrangian_DOF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Lagrangian" }));
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1.class);
    jComboBox_Lagrangian_DOF.setToolTipText(resourceMap.getString("jComboBox_Lagrangian_DOF.toolTipText")); // NOI18N
    jComboBox_Lagrangian_DOF.setName("jComboBox_Lagrangian_DOF"); // NOI18N
    jComboBox_Lagrangian_DOF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox_Lagrangian_DOFActionPerformed(evt);
      }
    });

    jComboBox_Eulerian_DOF.setMaximumRowCount(1000);
    jComboBox_Eulerian_DOF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Eulerian" }));
    jComboBox_Eulerian_DOF.setToolTipText(resourceMap.getString("jComboBox_Eulerian_DOF.toolTipText")); // NOI18N
    jComboBox_Eulerian_DOF.setName("jComboBox_Eulerian_DOF"); // NOI18N
    jComboBox_Eulerian_DOF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox_Eulerian_DOFActionPerformed(evt);
      }
    });

    buttonGroup_AddRemove.add(jToggleButton_Add);
    jToggleButton_Add.setText(resourceMap.getString("jToggleButton_Add.text")); // NOI18N
    jToggleButton_Add.setName("jToggleButton_Add"); // NOI18N
    jToggleButton_Add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton_AddActionPerformed(evt);
      }
    });

    buttonGroup_AddRemove.add(jToggleButton_Remove);
    jToggleButton_Remove.setText(resourceMap.getString("jToggleButton_Remove.text")); // NOI18N
    jToggleButton_Remove.setName("jToggleButton_Remove"); // NOI18N
    jToggleButton_Remove.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton_RemoveActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane_Lagrangian_ControlPts_BASIC1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jComboBox_Lagrangian_DOF, 0, 174, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox_Eulerian_DOF, 0, 162, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToggleButton_Add, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToggleButton_Remove, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jToggleButton_Add)
          .addComponent(jToggleButton_Remove)
          .addComponent(jComboBox_Lagrangian_DOF)
          .addComponent(jComboBox_Eulerian_DOF))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane_Lagrangian_ControlPts_BASIC1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox_Lagrangian_DOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Lagrangian_DOFActionPerformed

    if (evt.getActionCommand().equals("comboBoxChanged")) {

      String selectedName = (String) this.jComboBox_Lagrangian_DOF.getSelectedItem();

      if (selectedName != null) {
        selectedLagrangian = selectedName;

        /* if eulerian already selected then perform add or remove */
        int I_e = jComboBox_Eulerian_DOF.getSelectedIndex();

        if (I_e != 0) {
          this.performAddRemoveAction();
        }

      }

    } /* end of action command check */

  }//GEN-LAST:event_jComboBox_Lagrangian_DOFActionPerformed

  private void jComboBox_Eulerian_DOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Eulerian_DOFActionPerformed

    if (evt.getActionCommand().equals("comboBoxChanged")) {

      String selectedName = (String) this.jComboBox_Eulerian_DOF.getSelectedItem();

      if (selectedName != null) {
        selectedEulerian = selectedName;

        /* if lagrangian already selected then perform add or remove */
        int I_e = jComboBox_Lagrangian_DOF.getSelectedIndex();

        if (I_e != 0) {
          this.performAddRemoveAction();
        }

      }

    } /* end of action command check */

  }//GEN-LAST:event_jComboBox_Eulerian_DOFActionPerformed

  private void jToggleButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_AddActionPerformed

    flagMode = FLAG_MODE_ADD;

    performAddRemoveAction();

  }//GEN-LAST:event_jToggleButton_AddActionPerformed


  private void performAddRemoveAction() {

    if (flagMode == FLAG_MODE_ADD) {

      /* Use the selected Lagrangian and Eulerian, if both selected */
      SELM_Lagrangian lagrangian = getLagrangianFromName(selectedLagrangian);
      SELM_Eulerian eulerian     = getEulerianFromName(selectedEulerian);

      boolean flagLagrangianFound = false;
      boolean flagEulerianFound = false;

      /* add (check if already there ?) */
      if ((lagrangian != null) && (eulerian != null)) {

        /* consider the list of Lagrangian types and add the name to the list */
        SELM_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1 couplingOpData = (SELM_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).getCouplingOpDataFromModel();

        /* check to see if pair is already in the list */
        flagLagrangianFound = couplingOpData.lagrangianList.contains(lagrangian);
        flagEulerianFound = couplingOpData.eulerianList.contains(eulerian);

        /* if the pair is not already in the list then add it */
        if ((flagLagrangianFound == false) || (flagLagrangianFound == false)) {

          couplingOpData.lagrangianList.ensureCapacity(couplingOpData.lagrangianList.size() + 1);
          couplingOpData.lagrangianList.add(lagrangian);

          couplingOpData.eulerianList.ensureCapacity(couplingOpData.eulerianList.size() + 1);
          couplingOpData.eulerianList.add(eulerian);

          ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).setFromCouplingOpData(couplingOpData);

        }

        /* reset the selection to zero */
        selectedLagrangian = "";
        selectedEulerian = "";

        jComboBox_Lagrangian_DOF.setSelectedIndex(0);
        jComboBox_Eulerian_DOF.setSelectedIndex(0);

      } /* end not null */

    } /* end of add */


    if (flagMode == FLAG_MODE_REMOVE) {
      /* consider the list of Lagrangian types and remove the name from the list */
      SELM_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1 couplingOpData = (SELM_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).getCouplingOpDataFromModel();

      /* remove the lagrangian entries matching the selected name */
      SELM_Lagrangian lagrangian = null;
      SELM_Eulerian   eulerian   = null;

      for (int k = 0; k < couplingOpData.lagrangianList.size(); k++) {

        lagrangian = (SELM_Lagrangian) couplingOpData.lagrangianList.get(k);
        eulerian   = (SELM_Eulerian) couplingOpData.eulerianList.get(k);
        if ( (lagrangian.LagrangianName.equals(this.selectedLagrangian)) &&
             (eulerian.EulerianName.equals(this.selectedEulerian)) ) {
          couplingOpData.lagrangianList.remove(k);
          couplingOpData.eulerianList.remove(k);
        }

      }
      
      ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).setFromCouplingOpData(couplingOpData);

      /* reset the selection to zero */
      selectedLagrangian = "";
      selectedEulerian = "";

      jComboBox_Lagrangian_DOF.setSelectedIndex(0);
      jComboBox_Eulerian_DOF.setSelectedIndex(0);

    } /* end remove */

  }

  private void jToggleButton_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_RemoveActionPerformed

    flagMode = FLAG_MODE_REMOVE;

    performAddRemoveAction();

  }//GEN-LAST:event_jToggleButton_RemoveActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup_AddRemove;
  private javax.swing.JComboBox jComboBox_Eulerian_DOF;
  private javax.swing.JComboBox jComboBox_Lagrangian_DOF;
  private javax.swing.JScrollPane jScrollPane_Lagrangian_ControlPts_BASIC1;
  private javax.swing.JTable jTable_CouplingOp_TABLE1;
  private javax.swing.JToggleButton jToggleButton_Add;
  private javax.swing.JToggleButton jToggleButton_Remove;
  // End of variables declaration//GEN-END:variables

  public JTable getJTable() {
    return jTable_CouplingOp_TABLE1;
  }

  /* set data for displaying couplingOp DOF */
  @Override
  public void setData(SELM_CouplingOperator couplingOpData) {
    ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).setFromCouplingOpData(couplingOpData);
  }

  /* get data for displaying couplingOp DOF */
  @Override
  public SELM_CouplingOperator getData() {
    SELM_CouplingOperator couplingOp;

    couplingOp = ((TableModel_CouplingOperator_LAMMPS_SHEAR_UNIFORM1_FFTW3_TABLE1) (jTable_CouplingOp_TABLE1.getModel())).getCouplingOpDataFromModel();

    return couplingOp;

  }


  /* new March 2011 */
  public void fireCouplingOpChanged() {

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_COUPLINGOP_DATA", 0, 1);
    }

  }

  public void jTable_CouplingOp_tableChanged(TableModelEvent e) {
    //System.out.println("JPanel_CouplingOp_TABLE1: jTable_CouplingOp_tableChanged: changed event" + e);

    fireCouplingOpChanged();
  }


  public void updateLists() {

    /* == update lagrangian lists */
    String oldLagrangianSelectedName = (String) jComboBox_Lagrangian_DOF.getSelectedItem();
    
    /* update the combo box to reflect all lagrangians */
    jComboBox_Lagrangian_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_Lagrangian_tryToSetSelectionByName(oldLagrangianSelectedName);

    /* == update eulerian lists */
    String oldEulerianSelectedName = (String) jComboBox_Eulerian_DOF.getSelectedItem();

    /* update the combo box to reflect all eulerians */
    jComboBox_Eulerian_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_Eulerian_tryToSetSelectionByName(oldEulerianSelectedName);

  }

  private void jComboBox_Lagrangian_rebuild_list() {

    SELM_Lagrangian[] lagrangianList;

    /* == Get the lagrangian list from the ControlPts_BASIC1 table */
    lagrangianList = ((JTable_MainData)applSharedData.jTable_MainData).getLagrangianList();

    if (lagrangianList != null) {

      /* == Rebuild the list of lagrangians in the combo box */
      jComboBox_Lagrangian_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_Lagrangian_DOF.getSelectedItem(); /* save for later */
      jComboBox_Lagrangian_DOF.removeAllItems();
      jComboBox_Lagrangian_DOF.addItem("Choose Lagrangian");
      int N = lagrangianList.length;
      for (int k = 0; k < N; k++) {
        jComboBox_Lagrangian_DOF.addItem(lagrangianList[k].LagrangianName);
      }

      if (jComboBox_Lagrangian_DOF.getItemCount() > 0) {
        jComboBox_Lagrangian_tryToSetSelectionByName(oldSelectedName);
      } else if (jComboBox_Lagrangian_DOF.getItemCount() == 0) { /* no entries set to NULL panel */
        //setLagrangianPanelToNULL();
      }
      jComboBox_Lagrangian_flagRebuildingList = false;

    } else {/* end check lagrangianList != null */
      //setLagrangianPanelToNULL();
    }

  }

  void jComboBox_Lagrangian_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_Lagrangian_DOF.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_Lagrangian_DOF.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_Lagrangian_DOF.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_Lagrangian_DOF.setSelectedIndex(selectedIndex);
    }

  }

  private SELM_Lagrangian getLagrangianFromName(String name) {

    SELM_Lagrangian lagrangian = null;
    SELM_Lagrangian[] list     = applSharedData.jTable_MainData.getLagrangianList();

    for (int k = 0; k < list.length; k++) {
       if (list[k].LagrangianName.equals(name)) {
         lagrangian = list[k];
       }
    }

    return lagrangian;

  }

  private void jComboBox_Eulerian_rebuild_list() {

    SELM_Eulerian[] eulerianList;

    /* == Get the eulerian list from the ControlPts_BASIC1 table */
    eulerianList = ((JTable_MainData)applSharedData.jTable_MainData).getEulerianList();

    if (eulerianList != null) {

      /* == Rebuild the list of eulerians in the combo box */
      jComboBox_Eulerian_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_Eulerian_DOF.getSelectedItem(); /* save for later */
      jComboBox_Eulerian_DOF.removeAllItems();
      jComboBox_Eulerian_DOF.addItem("Choose Eulerian");
      int N = eulerianList.length;
      for (int k = 0; k < N; k++) {
        if (eulerianList[k].EulerianTypeStr.equals("LAMMPS_SHEAR_UNIFORM1_FFTW3")) {
          jComboBox_Eulerian_DOF.addItem(eulerianList[k].EulerianName);
        }
      }

      if (jComboBox_Eulerian_DOF.getItemCount() > 0) {
        jComboBox_Eulerian_tryToSetSelectionByName(oldSelectedName);
      } else if (jComboBox_Eulerian_DOF.getItemCount() == 0) { /* no entries set to NULL panel */
        //setEulerianPanelToNULL();
      }
      jComboBox_Eulerian_flagRebuildingList = false;

    } else {/* end check eulerianList != null */
      //setEulerianPanelToNULL();
    }

  }

  void jComboBox_Eulerian_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_Eulerian_DOF.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_Eulerian_DOF.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_Eulerian_DOF.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_Eulerian_DOF.setSelectedIndex(selectedIndex);
    }

  }

  private SELM_Eulerian getEulerianFromName(String name) {

    SELM_Eulerian eulerian = null;
    SELM_Eulerian[] list     = applSharedData.jTable_MainData.getEulerianList();

    for (int k = 0; k < list.length; k++) {
       if (list[k].EulerianName.equals(name)) {
         eulerian = list[k];
       }
    }

    return eulerian;

  }
  
}
