package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel;
import java.awt.Component;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * Panel for editing the this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Editor_Lagrangian_DOF extends javax.swing.JPanel {

    application_SharedData applSharedData = null;

    private JPanel_Model_View_RenderPanel jPanel_Render_ControlPts;
    
    private MouseListener jToggleButton_AddingPairs_MouseListener = null;
    private MouseListener jToggleButton_RemovingPairs_MouseListener = null;

    private boolean jComboBox_Lagrangian_flagRebuildingList = false;

    private TableModel[] jTable_Lagrangian_ModelList; /* used for switchable table data */

    private SELM_LagrangianRenderView[] lagrangianRenderViewList;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Lagrangian_DOF() {
      initComponents();
      //updateLists();
    }

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Lagrangian_DOF(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
      updateLists();

      /* add listener to the jTable_mainData for any changes there */
      applSharedData.jTable_MainData.getModel().addTableModelListener(new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_MainData_tableChanged(e);
        }
      });
    
    }
    
    void jTable_MainData_tableChanged(TableModelEvent e)  {
      updateLists(); /* update the comboBox and data on change */
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_Lagrangian_DOF = new javax.swing.JComboBox();
        jButton_InteractionList_Modify = new javax.swing.JButton();
        jLabel_Interaction = new javax.swing.JLabel();
        jPanel_LagrangianData = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("Lagrangian DOF Editor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jComboBox_Lagrangian_DOF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Lagrangian_DOF.setName("jComboBox_Lagrangian_DOF"); // NOI18N
        jComboBox_Lagrangian_DOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Lagrangian_DOFActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Editor_Lagrangian_DOF.class);
        jButton_InteractionList_Modify.setText(resourceMap.getString("jButton_InteractionList_Modify.text")); // NOI18N
        jButton_InteractionList_Modify.setName("jButton_InteractionList_Modify"); // NOI18N
        jButton_InteractionList_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InteractionList_ModifyActionPerformed(evt);
            }
        });

        jLabel_Interaction.setText(resourceMap.getString("jLabel_Interaction.text")); // NOI18N
        jLabel_Interaction.setName("jLabel_Interaction"); // NOI18N

        jPanel_LagrangianData.setName("jPanel_LagrangianData"); // NOI18N
        jPanel_LagrangianData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel_LagrangianDataPropertyChange(evt);
            }
        });
        jPanel_LagrangianData.setLayout(new javax.swing.BoxLayout(jPanel_LagrangianData, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Interaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Lagrangian_DOF, 0, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_InteractionList_Modify)
                .addContainerGap())
            .addComponent(jPanel_LagrangianData, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Interaction)
                    .addComponent(jComboBox_Lagrangian_DOF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_InteractionList_Modify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_LagrangianData, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  public void updateLists() {

    String oldSelectedName = (String) jComboBox_Lagrangian_DOF.getSelectedItem();
    
    /* setup the model for the lagrangian data */
    //jTable_Lagrangian_build_all_table_Models();

    //if ((jTable_Lagrangian_ModelList != null) && (jTable_Lagrangian_ModelList.length > 0)) {
    //  int entryI = jComboBox_Lagrangian_DOF.getSelectedIndex();
     // if (entryI >= 0) {
     //   jTable_Lagrangian_CONTROL_PTS.setModel(jTable_Lagrangian_ModelList[entryI]);
     // }
    //}

    /* update the combo box to reflect all lagrangians */
    jComboBox_Lagrangian_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_Lagrangian_tryToSetSelectionByName(oldSelectedName);

  }

    private void jButton_InteractionList_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InteractionList_ModifyActionPerformed

      /* tell the main application code to select the panel with Lagrangian DOF */
      Component[] componentList = this.applSharedData.jPanel_Tabbed_Main.getComponents();
      
      int selectIndex = -1;

      for (int k = 0; k < componentList.length; k++) {
        if (componentList[k].getName().equals("jPanel_Lagrangian_DOF")) {
          selectIndex = k;
        }
      }
        
      if (selectIndex != -1) {
         this.applSharedData.jPanel_Tabbed_Main.setSelectedIndex(selectIndex);
      }
      
    //  jButton_InteractionList_ModifyActionPerformed_OLD_WAY(evt);
      
    }

    private void jButton_InteractionList_ModifyActionPerformed_OLD_WAY(java.awt.event.ActionEvent evt) {

      JDialog_Edit_LagrangianList dialog;

      /* trigger opening of J_Edit_LagrangianList dialog */
      //Set up the dialog that the button brings up.
      dialog = new JDialog_Edit_LagrangianList();

      dialog.setAlwaysOnTop(true);

      /* == Get the lagrangian list from the main table */
      TableModel_MainData model
              = (TableModel_MainData) applSharedData.jTable_MainData.getModel();

      int col = 1;
      TableData_LagrangianList tableData_LagrangianList
              = (TableData_LagrangianList) model.getValueAt(model.paramIndex_Lagrangian_DOF, col);

      dialog.setDataValue(tableData_LagrangianList, model.paramName_Lagrangian_DOF, TableData_LagrangianList.class.toString());

      //dialog.addPropertyChangeListener(this);

      /* setup the responses to the dialog */
      dialog.addWindowListener(new WindowAdapter() {
        public void windowClosing(WindowEvent we) {
          JDialog_Edit_LagrangianList dialog = (JDialog_Edit_LagrangianList) we.getSource();
          dialog.firePropertyChange(dialog.ACTION_DIALOG_DONE, 1, 0);
        }
      });

      dialog.addPropertyChangeListener(new PropertyChangeListener() {

        public void propertyChange(PropertyChangeEvent e) {

          boolean DEBUG = true;
          String prop = e.getPropertyName();
          String code_str = this.getClass().getName();
          TableData_LagrangianList dataValue;

          JDialog_Edit_LagrangianList dialog = (JDialog_Edit_LagrangianList) e.getSource();

          if (prop.equals(dialog.ACTION_DIALOG_DONE)) {
            dataValue = (TableData_LagrangianList) dialog.getDataValue();

            TableModel_MainData model
                    = (TableModel_MainData) applSharedData.jTable_MainData.getModel();

            /* update the lagrangianList data structure */
            dialog.setVisible(false);

            dataValue = (TableData_LagrangianList) dialog.getDataValue();

            /* change the data in the table */
            model.setEntryByName(model.paramName_Lagrangian_DOF, dataValue);

            /* rebuild the combo list to reflect changes made */
            jComboBox_Lagrangian_rebuild_list();

          } /* ACTION_DIALOG_DONE */

        } /* end event from dialog */
      });

      /* show the newly created dialog window */
      dialog.setVisible(true);
    }//GEN-LAST:event_jButton_InteractionList_ModifyActionPerformed

    private void jComboBox_Lagrangian_DOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Lagrangian_DOFActionPerformed

      int entryI  = jComboBox_Lagrangian_DOF.getSelectedIndex();

      /* do not respond if we are only rebuilding the list */
      if (jComboBox_Lagrangian_flagRebuildingList == false) {

        /* == Change the panel and data to edit selected Lagrangian DOF */

        /* -- get the Lagrangian DOF data */
        SELM_Lagrangian[] lagrangianList = applSharedData.jTable_MainData.getLagrangianList();
        SELM_Lagrangian lagrangianDOF    = lagrangianList[entryI];

        setLagrangianData(lagrangianList[entryI]);

      }
      
    }//GEN-LAST:event_jComboBox_Lagrangian_DOFActionPerformed

  public void setLagrangianData(SELM_Lagrangian lagrangianDOF) {

    /* -- determine the appropriate panel type to use */
    int N;
    jPanel_Lagrangian = null;
    N = applSharedData.jPanel_Lagrangian_DOF_list.length;
    jPanel_Lagrangian_index = -1;
    for (int k = 0; k < N; k++) {

      if (applSharedData.jPanel_Lagrangian_DOF_list[k].getName().equals(lagrangianDOF.LagrangianTypeStr)) {
        jPanel_Lagrangian = (JPanel_Lagrangian) applSharedData.jPanel_Lagrangian_DOF_list[k];
        jPanel_Lagrangian_index = k;
      }

    }

    /* -- setup the panel data based on SELM_Lagrangian data structure */
    if (jPanel_Lagrangian != null) {
      jPanel_Lagrangian.setData(lagrangianDOF);

      /* -- set the panel to display in correct location */
      jPanel_LagrangianData.removeAll();
      jPanel_LagrangianData.add(jPanel_Lagrangian);
      jPanel_LagrangianData.validate();
      jPanel_LagrangianData.repaint();
    }

  }

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      
    }//GEN-LAST:event_formPropertyChange

    private void jPanel_LagrangianDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel_LagrangianDataPropertyChange
      //System.out.println("JPanel_LagrangianData Property Change triggered: " + evt.getPropertyName());

      if (jPanel_Lagrangian != null) {
        SELM_Lagrangian lagrangian = jPanel_Lagrangian.getData();

        SELM_Lagrangian[] lagrangianList = applSharedData.jTable_MainData.getLagrangianList();

        //lagrangianList[jPanel_Lagrangian_index] = lagrangian;

        applSharedData.jTable_MainData.setLagrangianDOF(lagrangianList);
      }
      
    }//GEN-LAST:event_jPanel_LagrangianDataPropertyChange

    
    private void jComboBox_Lagrangian_rebuild_list() {

    SELM_Lagrangian[] lagrangianList;

    /* == Get the lagrangian list from the ControlPts_BASIC1 table */
    lagrangianList = ((JTable_MainData)applSharedData.jTable_MainData).getLagrangianList();

    if (lagrangianList != null) {

      /* == Rebuild the list of lagrangians in the combo box */
      jComboBox_Lagrangian_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_Lagrangian_DOF.getSelectedItem(); /* save for later */
      jComboBox_Lagrangian_DOF.removeAllItems();
      int N = lagrangianList.length;
      for (int k = 0; k < N; k++) {
        jComboBox_Lagrangian_DOF.addItem(lagrangianList[k].LagrangianName);
      }

      if (jComboBox_Lagrangian_DOF.getItemCount() > 0) {
        jComboBox_Lagrangian_tryToSetSelectionByName(oldSelectedName);
      } else if (jComboBox_Lagrangian_DOF.getItemCount() == 0) { /* no entries set to NULL panel */
        setLagrangianPanelToNULL();
      }
      jComboBox_Lagrangian_flagRebuildingList = false;

    } else {/* end check lagrangianList != null */
      setLagrangianPanelToNULL();
    }

  }

  public void setLagrangianPanelToNULL() {
    this.setLagrangianData(new SELM_Lagrangian_NULL());
  }

  void jComboBox_Lagrangian_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_Lagrangian_DOF.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_Lagrangian_DOF.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_Lagrangian_DOF.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_Lagrangian_DOF.setSelectedIndex(selectedIndex);
    } 

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_InteractionList_Modify;
    private javax.swing.JComboBox jComboBox_Lagrangian_DOF;
    private javax.swing.JLabel jLabel_Interaction;
    private javax.swing.JPanel jPanel_LagrangianData;
    // End of variables declaration//GEN-END:variables

  private JPanel_Lagrangian jPanel_Lagrangian = null;
  private int jPanel_Lagrangian_index = -1;

}
