package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel;
import java.awt.Component;
import java.awt.event.MouseListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * Panel for editing the this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Editor_CouplingOperator extends javax.swing.JPanel {

    application_SharedData applSharedData = null;

    private JPanel_Model_View_RenderPanel jPanel_Render_ControlPts;
    
    private MouseListener jToggleButton_AddingPairs_MouseListener = null;
    private MouseListener jToggleButton_RemovingPairs_MouseListener = null;

    private boolean jComboBox_CouplingOp_flagRebuildingList = false;

    private TableModel[] jTable_CouplingOp_ModelList; /* used for switchable table data */

    //private SELM_CouplingOpRenderView[] couplingOpRenderViewList;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_CouplingOperator() {
      initComponents();
      //updateLists();
    }

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_CouplingOperator(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
      updateLists();

      /* add listener to the jTable_mainData for any changes there */
      applSharedData.jTable_MainData.getModel().addTableModelListener(new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_MainData_tableChanged(e);
        }
      });
    
    }
    
    void jTable_MainData_tableChanged(TableModelEvent e)  {
      updateLists(); /* update the comboBox and data on change */
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_CouplingOp = new javax.swing.JComboBox();
        jButton_CouplingOp_Modify = new javax.swing.JButton();
        jLabel_CouplingOp = new javax.swing.JLabel();
        jPanel_CouplingOpData = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("Coupling Operator Editor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jComboBox_CouplingOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_CouplingOp.setName("jComboBox_CouplingOp"); // NOI18N
        jComboBox_CouplingOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CouplingOpActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Editor_CouplingOperator.class);
        jButton_CouplingOp_Modify.setText(resourceMap.getString("jButton_CouplingOp_Modify.text")); // NOI18N
        jButton_CouplingOp_Modify.setName("jButton_CouplingOp_Modify"); // NOI18N
        jButton_CouplingOp_Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CouplingOp_ModifyActionPerformed(evt);
            }
        });

        jLabel_CouplingOp.setText(resourceMap.getString("jLabel_CouplingOp.text")); // NOI18N
        jLabel_CouplingOp.setName("jLabel_CouplingOp"); // NOI18N

        jPanel_CouplingOpData.setName("jPanel_CouplingOpData"); // NOI18N
        jPanel_CouplingOpData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel_CouplingOpDataPropertyChange(evt);
            }
        });
        jPanel_CouplingOpData.setLayout(new javax.swing.BoxLayout(jPanel_CouplingOpData, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_CouplingOp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_CouplingOp, 0, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CouplingOp_Modify)
                .addContainerGap())
            .addComponent(jPanel_CouplingOpData, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CouplingOp)
                    .addComponent(jComboBox_CouplingOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CouplingOp_Modify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_CouplingOpData, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  public void updateLists() {

    String oldSelectedName = (String) jComboBox_CouplingOp.getSelectedItem();
    
    /* setup the model for the couplingOp data */
    //jTable_CouplingOp_build_all_table_Models();

    //if ((jTable_CouplingOp_ModelList != null) && (jTable_CouplingOp_ModelList.length > 0)) {
    //  int entryI = jComboBox_CouplingOp_DOF.getSelectedIndex();
     // if (entryI >= 0) {
     //   jTable_CouplingOp_CONTROL_PTS.setModel(jTable_CouplingOp_ModelList[entryI]);
     // }
    //}

    /* update the combo box to reflect all couplingOps */
    jComboBox_CouplingOp_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_CouplingOp_tryToSetSelectionByName(oldSelectedName);

  }

    private void jButton_CouplingOp_ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CouplingOp_ModifyActionPerformed

      /* tell the main application code to select the panel with Lagrangian DOF */
      Component[] componentList = this.applSharedData.jPanel_Tabbed_Main.getComponents();

      int selectIndex = -1;

      for (int k = 0; k < componentList.length; k++) {
        if (componentList[k].getName().equals("jPanel_CouplingOp")) {
          selectIndex = k;
        }
      }

      if (selectIndex != -1) {
         this.applSharedData.jPanel_Tabbed_Main.setSelectedIndex(selectIndex);
      }
//
//
//
//      JDialog_Edit_CouplingOperatorList dialog;
//
//      /* trigger opening of J_Edit_CouplingOpList dialog */
//      //Set up the dialog that the button brings up.
//      dialog = new JDialog_Edit_CouplingOperatorList();
//
//      dialog.setAlwaysOnTop(true);
//
//      /* == Get the couplingOp list from the main table */
//      TableModel_MainData model
//              = (TableModel_MainData) applSharedData.jTable_MainData.getModel();
//
//      int col = 1;
//      TableData_CouplingOperatorList tableData_CouplingOpList
//              = (TableData_CouplingOperatorList) model.getValueAt(model.paramIndex_CouplingOpList, col);
//
//      dialog.setDataValue(tableData_CouplingOpList, model.paramName_CouplingOpList, TableData_CouplingOperatorList.class.toString());
//
//      //dialog.addPropertyChangeListener(this);
//
//      /* setup the responses to the dialog */
//      dialog.addWindowListener(new WindowAdapter() {
//        public void windowClosing(WindowEvent we) {
//          JDialog_Edit_CouplingOperatorList dialog = (JDialog_Edit_CouplingOperatorList) we.getSource();
//          dialog.firePropertyChange(dialog.ACTION_DIALOG_DONE, 1, 0);
//        }
//      });
//
//      dialog.addPropertyChangeListener(new PropertyChangeListener() {
//
//        public void propertyChange(PropertyChangeEvent e) {
//
//          boolean DEBUG = true;
//          String prop = e.getPropertyName();
//          String code_str = this.getClass().getName();
//          TableData_CouplingOperatorList dataValue;
//
//          JDialog_Edit_CouplingOperatorList dialog = (JDialog_Edit_CouplingOperatorList) e.getSource();
//
//          if (prop.equals(dialog.ACTION_DIALOG_DONE)) {
//            dataValue = (TableData_CouplingOperatorList) dialog.getDataValue();
//
//            TableModel_MainData model
//                    = (TableModel_MainData) applSharedData.jTable_MainData.getModel();
//
//            /* update the couplingOpList data structure */
//            dialog.setVisible(false);
//
//            dataValue = (TableData_CouplingOperatorList) dialog.getDataValue();
//
//            /* change the data in the table */
//            model.setEntryByName(model.paramName_CouplingOpList, dataValue);
//
//            /* rebuild the combo list to reflect changes made */
//            jComboBox_CouplingOp_rebuild_list();
//
//          } /* ACTION_DIALOG_DONE */
//
//        } /* end event from dialog */
//      });
//
//      /* show the newly created dialog window */
//      dialog.setVisible(true);
      
    }//GEN-LAST:event_jButton_CouplingOp_ModifyActionPerformed

    
    private void jComboBox_CouplingOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CouplingOpActionPerformed

      int entryI  = jComboBox_CouplingOp.getSelectedIndex();

      /* do not respond if we are only rebuilding the list */
      if (jComboBox_CouplingOp_flagRebuildingList == false) {

        /* == Change the panel and data to edit selected CouplingOp DOF */

        /* -- get the CouplingOp DOF data */
        SELM_CouplingOperator[] couplingOpList = applSharedData.jTable_MainData.getCouplingOpList();
        SELM_CouplingOperator couplingOp       = couplingOpList[entryI];

        setCouplingOpData(couplingOp);
      }
      
    }//GEN-LAST:event_jComboBox_CouplingOpActionPerformed

  public void setCouplingOpData(SELM_CouplingOperator couplingOp) {
    
    /* -- determine the appropriate panel type to use */
    int N;
    jPanel_CouplingOp = null;
    N = applSharedData.jPanel_CouplingOp_list.length;
    jPanel_CouplingOp_index = -1;
    for (int k = 0; k < N; k++) {

      if (applSharedData.jPanel_CouplingOp_list[k].getName().equals(couplingOp.CouplingOpTypeStr)) {
        jPanel_CouplingOp = (JPanel_CouplingOperator) applSharedData.jPanel_CouplingOp_list[k];
        jPanel_CouplingOp_index = k;
      }

    }

    /* -- setup the panel data based on SELM_CouplingOperator data structure */
    jPanel_CouplingOp.setData(couplingOp);

    /* -- set the panel to display in correct location */
    jPanel_CouplingOpData.removeAll();
    jPanel_CouplingOpData.add(jPanel_CouplingOp);
    jPanel_CouplingOpData.validate();
    jPanel_CouplingOpData.repaint();

  }


    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      
    }//GEN-LAST:event_formPropertyChange

    private void jPanel_CouplingOpDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel_CouplingOpDataPropertyChange

      //System.out.println("JPanel_CouplingOpData Property Change triggered: " + evt.getPropertyName());

      if (jPanel_CouplingOp != null) {
        SELM_CouplingOperator couplingOp = jPanel_CouplingOp.getData();

        SELM_CouplingOperator[] couplingOpList = applSharedData.jTable_MainData.getCouplingOpList();

        //if (couplingOp != null)
            //System.out.println("couplingOp = " + couplingOp.toString());

        //couplingOpList[jPanel_CouplingOp_index] = couplingOp;

        applSharedData.jTable_MainData.setCouplingOpList(couplingOpList);
        
        //this.validate();
        //this.repaint();
        //jPanel_CouplingOp.setData(couplingOp);
        jPanel_CouplingOp.validate();
        jPanel_CouplingOp.repaint();

      }
      
    }//GEN-LAST:event_jPanel_CouplingOpDataPropertyChange

    private void jComboBox_CouplingOp_rebuild_list() {

    SELM_CouplingOperator[] couplingOpList;

    /* == Get the couplingOp list from the ControlPts_BASIC1 table */
    couplingOpList = ((JTable_MainData)applSharedData.jTable_MainData).getCouplingOpList();

    if (couplingOpList != null) {

      /* == Rebuild the list of couplingOps in the combo box */
      jComboBox_CouplingOp_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_CouplingOp.getSelectedItem(); /* save for later */
      jComboBox_CouplingOp.removeAllItems();
      int N = couplingOpList.length;
      for (int k = 0; k < N; k++) {
        jComboBox_CouplingOp.addItem(couplingOpList[k].CouplingOpName);
      }
      if (jComboBox_CouplingOp.getItemCount() > 0) {
        jComboBox_CouplingOp_tryToSetSelectionByName(oldSelectedName);
      } else { /* no items in the list */
        setCouplingOpPanelToNULL();
      }
      jComboBox_CouplingOp_flagRebuildingList = false;

    } else {/* end check couplingOpList != null */
      setCouplingOpPanelToNULL();
    }

  }

  public void setCouplingOpPanelToNULL() {
    this.setCouplingOpData(new SELM_CouplingOperator_NULL());
  }

  void jComboBox_CouplingOp_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_CouplingOp.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_CouplingOp.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_CouplingOp.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_CouplingOp.setSelectedIndex(selectedIndex);
    }

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CouplingOp_Modify;
    private javax.swing.JComboBox jComboBox_CouplingOp;
    private javax.swing.JLabel jLabel_CouplingOp;
    private javax.swing.JPanel jPanel_CouplingOpData;
    // End of variables declaration//GEN-END:variables

  private JPanel_CouplingOperator jPanel_CouplingOp = null;
  private int jPanel_CouplingOp_index = -1;

}
