package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel;
import java.awt.Component;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;

/**
 *
 * Panel for editing the this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Editor_Eulerian_DOF extends javax.swing.JPanel {

    application_SharedData applSharedData = null;

    private JPanel_Model_View_RenderPanel jPanel_Render_ControlPts;
    
    private MouseListener jToggleButton_AddingPairs_MouseListener = null;
    private MouseListener jToggleButton_RemovingPairs_MouseListener = null;

    private boolean jComboBox_Eulerian_flagRebuildingList = false;

    private TableModel[] jTable_Eulerian_ModelList; /* used for switchable table data */

    private SELM_EulerianRenderView[] eulerianRenderViewList;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Eulerian_DOF() {
      initComponents();

      /* create empty panel ?*/

      /* set application data later */
      
    }

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Editor_Eulerian_DOF(application_SharedData applSharedData_in) {      
      initComponents();
      init(applSharedData_in);
    }

    public void init(application_SharedData applSharedData_in) {

      applSharedData = applSharedData_in;

      updateLists();

      /* add listener to the jTable_mainData for any changes there */
      applSharedData.jTable_MainData.getModel().addTableModelListener(new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_MainData_tableChanged(e);
        }
      });
      
    }

    public void setApplSharedData(application_SharedData applSharedData_in) {      
      init(applSharedData_in);
    }
    
    void jTable_MainData_tableChanged(TableModelEvent e)  {
      updateLists(); /* update the comboBox and data on change */
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_Eulerian_DOF = new javax.swing.JComboBox();
        jLabel_Eulerian = new javax.swing.JLabel();
        jPanel_EulerianData = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("Lagrangian DOF Editor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jComboBox_Eulerian_DOF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Eulerian_DOF.setName("jComboBox_Eulerian_DOF"); // NOI18N
        jComboBox_Eulerian_DOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Eulerian_DOFActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Editor_Eulerian_DOF.class);
        jLabel_Eulerian.setText(resourceMap.getString("jLabel_Eulerian.text")); // NOI18N
        jLabel_Eulerian.setName("jLabel_Eulerian"); // NOI18N

        jPanel_EulerianData.setName("jPanel_EulerianData"); // NOI18N
        jPanel_EulerianData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel_EulerianDataPropertyChange(evt);
            }
        });
        jPanel_EulerianData.setLayout(new javax.swing.BoxLayout(jPanel_EulerianData, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Eulerian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Eulerian_DOF, 0, 156, Short.MAX_VALUE)
                .addGap(279, 279, 279))
            .addComponent(jPanel_EulerianData, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Eulerian)
                    .addComponent(jComboBox_Eulerian_DOF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_EulerianData, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  public void updateLists() {

    String oldSelectedName = (String) jComboBox_Eulerian_DOF.getSelectedItem();
    
    /* setup the model for the eulerian data */
    //jTable_Eulerian_build_all_table_Models();

    //if ((jTable_Eulerian_ModelList != null) && (jTable_Eulerian_ModelList.length > 0)) {
    //  int entryI = jComboBox_Eulerian_DOF.getSelectedIndex();
     // if (entryI >= 0) {
     //   jTable_Eulerian_CONTROL_PTS.setModel(jTable_Eulerian_ModelList[entryI]);
     // }
    //}

    /* update the combo box to reflect all eulerians */
    jComboBox_Eulerian_rebuild_list();

    /* try to select the old entry before changes were made */
    jComboBox_Eulerian_tryToSetSelectionByName(oldSelectedName);

  }

    private void jComboBox_Eulerian_DOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Eulerian_DOFActionPerformed

      int entryI  = jComboBox_Eulerian_DOF.getSelectedIndex();

      /* do not respond if we are only rebuilding the list */
      if (jComboBox_Eulerian_flagRebuildingList == false) {

        /* == Change the panel and data to edit selected Eulerian DOF */

        /* -- get the Eulerian DOF data */
        SELM_Eulerian[] eulerianList = applSharedData.jTable_MainData.getEulerianList();
        SELM_Eulerian eulerianDOF    = eulerianList[entryI];

        setEulerianData(eulerianList[entryI]);

      }
      
    }//GEN-LAST:event_jComboBox_Eulerian_DOFActionPerformed

  public void setEulerianData(SELM_Eulerian eulerianDOF) {

    /* -- determine the appropriate panel type to use */
    int N;
    jPanel_Eulerian = null;
    N = applSharedData.jPanel_Eulerian_DOF_list.length;
    jPanel_Eulerian_index = -1;
    for (int k = 0; k < N; k++) {

      if (applSharedData.jPanel_Eulerian_DOF_list[k].getName().equals(eulerianDOF.EulerianTypeStr)) {
        jPanel_Eulerian = (JPanel_Eulerian) applSharedData.jPanel_Eulerian_DOF_list[k];
        jPanel_Eulerian_index = k;
      }

    }

    /* -- setup the panel data based on SELM_Eulerian data structure */
    jPanel_Eulerian.setData(eulerianDOF);

    /* -- set the panel to display in correct location */
    jPanel_EulerianData.removeAll();
    jPanel_EulerianData.add(jPanel_Eulerian);
    jPanel_EulerianData.validate();
    jPanel_EulerianData.repaint();

  }

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
      
    }//GEN-LAST:event_formPropertyChange

    private void jPanel_EulerianDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel_EulerianDataPropertyChange
      //System.out.println("JPanel_EulerianData Property Change triggered: " + evt.getPropertyName());

      if (jPanel_Eulerian != null) {
        SELM_Eulerian eulerian = jPanel_Eulerian.getData();

        SELM_Eulerian[] eulerianList = applSharedData.jTable_MainData.getEulerianList();

        //eulerianList[jPanel_Eulerian_index] = eulerian;

        applSharedData.jTable_MainData.setEulerianDOF(eulerianList);
      }
      
    }//GEN-LAST:event_jPanel_EulerianDataPropertyChange

    
    private void jComboBox_Eulerian_rebuild_list() {

    SELM_Eulerian[] eulerianList;

    /* == Get the eulerian list from the ControlPts_BASIC1 table */
    eulerianList = ((JTable_MainData)applSharedData.jTable_MainData).getEulerianList();

    if (eulerianList != null) {

      /* == Rebuild the list of eulerians in the combo box */
      jComboBox_Eulerian_flagRebuildingList = true;  /* signal reconstructing */
      String oldSelectedName = (String)jComboBox_Eulerian_DOF.getSelectedItem(); /* save for later */
      jComboBox_Eulerian_DOF.removeAllItems();
      int N = eulerianList.length;
      for (int k = 0; k < N; k++) {
        jComboBox_Eulerian_DOF.addItem(eulerianList[k].EulerianName);
      }

      if (jComboBox_Eulerian_DOF.getItemCount() > 0) {
        jComboBox_Eulerian_tryToSetSelectionByName(oldSelectedName);
      } else if (jComboBox_Eulerian_DOF.getItemCount() == 0) { /* no entries set to NULL panel */
        setEulerianPanelToNULL();
      }
      jComboBox_Eulerian_flagRebuildingList = false;

    } else {/* end check eulerianList != null */
      setEulerianPanelToNULL();
    }

  }

  public void setEulerianPanelToNULL() {
    this.setEulerianData(new SELM_Eulerian_NULL());
  }

  void jComboBox_Eulerian_tryToSetSelectionByName(String nameTrySelect) {

    if (jComboBox_Eulerian_DOF.getItemCount() > 0) {
      int selectedIndex = 0; /* if can't find set to zero index */
      int N = jComboBox_Eulerian_DOF.getItemCount();
      for (int k = 0; k < N; k++) {
        String name = (String) jComboBox_Eulerian_DOF.getItemAt(k);
        if (name.equals(nameTrySelect)) {
          selectedIndex = k;
        }
      }
      jComboBox_Eulerian_DOF.setSelectedIndex(selectedIndex);
    } 

  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox_Eulerian_DOF;
    private javax.swing.JLabel jLabel_Eulerian;
    private javax.swing.JPanel jPanel_EulerianData;
    // End of variables declaration//GEN-END:variables

  private JPanel_Eulerian jPanel_Eulerian = null;
  private int jPanel_Eulerian_index = -1;

}
