package org.atzberger.application.selm_builder;

import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing attributes of a specific data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_CouplingOperator_NULL extends JPanel_CouplingOperator {

  public application_SharedData applSharedData = null;

    public JPanel_CouplingOperator_NULL(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
      
    }


    /** Creates new form JPanel_CouplingOp_ControlPts_BASIC1 */
    public JPanel_CouplingOperator_NULL() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setName("NULL"); // NOI18N

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setName("jLabel1"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(138, 138, 138)
        .addComponent(jLabel1)
        .addContainerGap(147, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables


  @Override
  public void setData(SELM_CouplingOperator couplingOp) {
    
  }

  @Override
  public SELM_CouplingOperator getData() {
    return null;
  }

  public void jTable_CouplingOp_tableChanged(TableModelEvent e) {
    //System.out.println("jTable_Lagrangian changed event" + e);

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_COUPLING_OP_DATA", 0, 1);
    }

  }


}
