package org.atzberger.application.selm_builder;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing the list of named data of this type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Edit_InteractionList extends javax.swing.JPanel {

  application_SharedData applSharedData = null;

  String [] listInteractionKnownTypesStr = new String[0];

  /** Creates new form JPanel_Edit_InteractionList */
  public JPanel_Edit_InteractionList() {
    initComponents();

    jTable_InteractionList.getModel().addTableModelListener(new TableModelListener() {
      public void tableChanged(TableModelEvent e)  {
        jTable_InteractionList_tableChanged(e);
      }
    });

  }

  public JPanel_Edit_InteractionList(application_SharedData applSharedData_in) {
    this(); /* call constructor */
    applSharedData = applSharedData_in;    
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel_Organize_Controls = new javax.swing.JPanel();
    jButton_Edit_CouplingOp = new javax.swing.JButton();
    jComboBox_Add_Interaction = new javax.swing.JComboBox();
    jButton_Remove_Interaction = new javax.swing.JButton();
    jScrollPane_Table_Interactions = new javax.swing.JScrollPane();
    jTable_InteractionList = (JTable) new org.atzberger.mango.table.JTable_Properties1_Default();

    setName("Form"); // NOI18N
    setPreferredSize(new java.awt.Dimension(700, 312));

    jPanel_Organize_Controls.setName("jPanel_Organize_Controls"); // NOI18N
    jPanel_Organize_Controls.setPreferredSize(new java.awt.Dimension(500, 69));

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Edit_InteractionList.class);
    jButton_Edit_CouplingOp.setText(resourceMap.getString("jButton_Edit_CouplingOp.text")); // NOI18N
    jButton_Edit_CouplingOp.setName("jButton_Edit_CouplingOp"); // NOI18N
    jButton_Edit_CouplingOp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_Edit_CouplingOpActionPerformed(evt);
      }
    });

    jComboBox_Add_Interaction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Interaction", "Item 1", "Item 2" }));
    jComboBox_Add_Interaction.setName("jComboBox_Add_Interaction"); // NOI18N
    jComboBox_Add_Interaction.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox_Add_InteractionActionPerformed(evt);
      }
    });

    jButton_Remove_Interaction.setText(resourceMap.getString("jButton_Remove_Interaction.text")); // NOI18N
    jButton_Remove_Interaction.setName("jButton_Remove_Interaction"); // NOI18N
    jButton_Remove_Interaction.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton_Remove_InteractionActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel_Organize_ControlsLayout = new javax.swing.GroupLayout(jPanel_Organize_Controls);
    jPanel_Organize_Controls.setLayout(jPanel_Organize_ControlsLayout);
    jPanel_Organize_ControlsLayout.setHorizontalGroup(
      jPanel_Organize_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_Organize_ControlsLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jComboBox_Add_Interaction, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButton_Edit_CouplingOp)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        .addComponent(jButton_Remove_Interaction)
        .addContainerGap())
    );
    jPanel_Organize_ControlsLayout.setVerticalGroup(
      jPanel_Organize_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel_Organize_ControlsLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(jPanel_Organize_ControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton_Edit_CouplingOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jComboBox_Add_Interaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton_Remove_Interaction))
        .addContainerGap())
    );

    jScrollPane_Table_Interactions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jScrollPane_Table_Interactions.setName("jScrollPane_Table_Interactions"); // NOI18N

    jTable_InteractionList.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("jTable_InteractionList.border.lineColor"))); // NOI18N
    jTable_InteractionList.setModel(new org.atzberger.application.selm_builder.TableModel_InteractionList());
    jTable_InteractionList.setName("jTable_InteractionList"); // NOI18N
    jScrollPane_Table_Interactions.setViewportView(jTable_InteractionList);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel_Organize_Controls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(jScrollPane_Table_Interactions, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        .addGap(12, 12, 12))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane_Table_Interactions, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel_Organize_Controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

    private void jButton_Edit_CouplingOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_CouplingOpActionPerformed
      applSharedData.FrameView_Application_Main.openInDockableWindowPanel(applSharedData.FrameView_Application_Main.jPanel_Editor_Interaction);
}//GEN-LAST:event_jButton_Edit_CouplingOpActionPerformed

    private void jComboBox_Add_InteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Add_InteractionActionPerformed

      Atz_Object_Factory atz_Object_Factory = null;

      if (evt.getActionCommand().equals("comboBoxChanged")) {

        String selectedType = (String) jComboBox_Add_Interaction.getSelectedItem();

        if (selectedType != null) {

          SELM_Interaction newInteraction = null;
          SELM_Interaction[] interactionList_new;
          SELM_Interaction[] interactionList = applSharedData.jTable_MainData.getInteractionList();

          /* loop over the Interaction types and instantiate a class of the appropriate type */
          for (int k = 0; k < applSharedData.jPanel_Interaction_list.length; k++) {
            JPanel_Interaction jPanel_Interaction = applSharedData.jPanel_Interaction_list[k];
            
            if (selectedType.equals(jPanel_Interaction.getName())) {

              atz_Object_Factory = jPanel_Interaction.getObjectFactory();

              if (atz_Object_Factory == null) {  /* use default approach (deprecated) */
              
                String packageName   = this.getClass().getPackage().getName();//"pja_desktopapplication1";
                String startsWithStr = "SELM_Interaction_";
                String className     = packageName + "." + startsWithStr + jPanel_Interaction.getName();

                newInteraction = (SELM_Interaction) Atz_ClassLoader.loadAndInstantiateClass(className, this.getClass().getClassLoader());

              } else {
                newInteraction = (SELM_Interaction) atz_Object_Factory.getNewInstance();
              }

            } /* end match of Interaction selected name */
                          
          } /* end of k loop */

          if (newInteraction != null) {
            /* add the interaction to the list */
            int N = interactionList.length;
            interactionList_new = new SELM_Interaction[N + 1];
            System.arraycopy(interactionList, 0,
              interactionList_new, 0, N);

            interactionList_new[N] = newInteraction;

            interactionList = interactionList_new;

            applSharedData.jTable_MainData.setInteractionList(interactionList);
          }

          /* reset the selection to zero */
          jComboBox_Add_Interaction.setSelectedIndex(0);

        }

      } /* end of action command check */

    }//GEN-LAST:event_jComboBox_Add_InteractionActionPerformed

    private void jButton_Remove_InteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Remove_InteractionActionPerformed

      /* Determine the selected rows and remove entries from the interactionList */
      int selectedRows[] = jTable_InteractionList.getSelectedRows();

      if (selectedRows.length > 0) {

        int k;
        SELM_Interaction[] interactionList = applSharedData.jTable_MainData.getInteractionList();
        int N = interactionList.length;
        int mask[] = new int[N];
        int I;
        int newN;
        SELM_Interaction[] interactionList_new;

        for (k = 0; k < N; k++) {
          mask[k] = 1; /* indicates to keep this entry */
        }

        newN = N;
        for (k = 0; k < selectedRows.length; k++) {
          I = selectedRows[k];
          mask[I] = 0; /* indicates this is row to delete */
          newN--;
        }

        interactionList_new = new SELM_Interaction[newN];
        I = 0;
        for (k = 0; k < N; k++) {
          if (mask[k] == 1) {
            interactionList_new[I] = interactionList[k];
            I++;
          }
        }

        interactionList = interactionList_new;

        applSharedData.jTable_MainData.setInteractionList(interactionList);

        /* set the selected row */
        if (selectedRows[0] < newN) {
          jTable_InteractionList.setRowSelectionInterval(selectedRows[0], selectedRows[0]);
        } else if (newN > 0) {
          jTable_InteractionList.setRowSelectionInterval(newN - 1, newN - 1);
        }

      }
    }//GEN-LAST:event_jButton_Remove_InteractionActionPerformed

 
    public void jTable_InteractionList_tableChanged(TableModelEvent e)  {

    /* update the interaction names using the table values */
    if (jTable_InteractionList_validForUse) {

      SELM_Interaction[] InteractionList  = applSharedData.jTable_MainData.getInteractionList();
      TableModel_InteractionList model   = (TableModel_InteractionList) jTable_InteractionList.getModel();

      for (int k = 0; k < InteractionList.length; k++) {
        (InteractionList[k]).InteractionName = (String) model.getValueAt(k,0); /* interaction name */
      }

      /* set the interaction list (notify of changes) */
      applSharedData.jTable_MainData.setInteractionList(InteractionList);
    }

  }

  public void setInteractionKnownTypes(String[] listInteractionKnownTypesStr_in) {

    listInteractionKnownTypesStr = listInteractionKnownTypesStr_in;

    jComboBox_Add_Interaction.removeAllItems();
    jComboBox_Add_Interaction.addItem("Add Interaction");
    for (int k = 0; k < applSharedData.jPanel_Interaction_list.length; k++) {
      jComboBox_Add_Interaction.addItem(listInteractionKnownTypesStr[k]);
    }

    repaint();
  }

  public String[] getInteractionKnownTypes() {
    return listInteractionKnownTypesStr;
  }
  
  public void setTableFromInteractionList(SELM_Interaction[] InteractionList) {

    TableModel_InteractionList model  = (TableModel_InteractionList) jTable_InteractionList.getModel();

    jTable_InteractionList_validForUse = false; /* indicates rebuilding table */
    model.removeAllEntries();
    for (int k = 0; k < InteractionList.length; k++) {
      model.setValueAt((InteractionList[k]).InteractionName, k, 0, TableModel_InteractionList.EDITABLE);
      model.setValueAt((InteractionList[k]).InteractionTypeStr, k, 1, TableModel_InteractionList.NOT_EDITABLE);

      model.fireTableCellUpdated(k, 0);
      model.fireTableCellUpdated(k, 1);
    }
    jTable_InteractionList_validForUse = true;

  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton_Edit_CouplingOp;
  private javax.swing.JButton jButton_Remove_Interaction;
  private javax.swing.JComboBox jComboBox_Add_Interaction;
  private javax.swing.JPanel jPanel_Organize_Controls;
  private javax.swing.JScrollPane jScrollPane_Table_Interactions;
  private javax.swing.JTable jTable_InteractionList;
  // End of variables declaration//GEN-END:variables

  public boolean jTable_InteractionList_validForUse  = false;

}
