package org.atzberger.application.selm_builder;

import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing attributes of a specific data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_CouplingOperator_IB1 extends JPanel_CouplingOperator {

  public application_SharedData applSharedData = null;

    public JPanel_CouplingOperator_IB1(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();

      /* add listener to the jTable_CouplingOp for any changes there */
      jTable_CouplingOp.getModel().addTableModelListener(new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_CouplingOp_tableChanged(e);
        }
      });

      
    }


    /** Creates new form JPanel_CouplingOp_ControlPts_BASIC1 */
    public JPanel_CouplingOperator_IB1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane_CouplingOp = new javax.swing.JScrollPane();
    jTable_CouplingOp = new org.atzberger.application.selm_builder.JTable_Lagrangian_ControlPts_BASIC1(new org.atzberger.application.selm_builder.TableModel_CouplingOperator_TABLE1_tmp(applSharedData));

    setName("IB1"); // NOI18N

    jScrollPane_CouplingOp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    jScrollPane_CouplingOp.setName("jScrollPane_CouplingOp"); // NOI18N

    jTable_CouplingOp.setBorder(javax.swing.BorderFactory.createLineBorder(null));
    jTable_CouplingOp.setModel(new org.atzberger.application.selm_builder.TableModel_CouplingOperator_IB1(applSharedData.atz_UnitsRef));
    jTable_CouplingOp.setName("jTable_CouplingOp"); // NOI18N
    jScrollPane_CouplingOp.setViewportView(jTable_CouplingOp);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane_CouplingOp, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(54, Short.MAX_VALUE)
        .addComponent(jScrollPane_CouplingOp, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane_CouplingOp;
  private javax.swing.JTable jTable_CouplingOp;
  // End of variables declaration//GEN-END:variables


  @Override
  public void setData(SELM_CouplingOperator couplingOp) {
    ((TableModel_CouplingOperator_IB1)(jTable_CouplingOp.getModel())).setFromCouplingOpData(couplingOp);
  }

  @Override
  public SELM_CouplingOperator getData() {
    SELM_CouplingOperator couplingOp;

    couplingOp = ((TableModel_CouplingOperator_IB1)(jTable_CouplingOp.getModel())).getCouplingOpDataFromModel();

    return couplingOp;
  }

  public void jTable_CouplingOp_tableChanged(TableModelEvent e) {
    //System.out.println("jTable_Lagrangian changed event" + e);

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_COUPLING_OP_DATA", 0, 1);
    }

  }


}
