package org.atzberger.application.selm_builder;

/**
 *
 * Panel for editing this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Integrator_BD1 extends JPanel_Integrator {

  application_SharedData applSharedData = null;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Integrator_BD1() {
        initComponents();
    }

    public JPanel_Integrator_BD1(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();

    setMinimumSize(new java.awt.Dimension(400, 200));
    setName("BD1"); // NOI18N
    setPreferredSize(new java.awt.Dimension(400, 200));

    jLabel1.setName("jLabel1"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(83, 83, 83)
        .addComponent(jLabel1)
        .addContainerGap(135, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(75, 75, 75)
        .addComponent(jLabel1)
        .addContainerGap(109, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables

}
