package org.atzberger.application.selm_builder;

import org.atzberger.mango.atz3d.Atz3D_Model;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Interaction_NULL extends JPanel_Interaction implements SELM_InteractionRenderView {

  public application_SharedData applSharedData = null;

  public JPanel_Interaction_NULL(application_SharedData applSharedData_in) {
    applSharedData = applSharedData_in;
    initComponents();
    modifyComponents();
    
  }

  public void jTable_Interaction_tableChanged(TableModelEvent e)  {
    System.out.println("jTable_Interaction changed event" + e);

    fireInteractionChanged();

  }

  
  public void fireInteractionChanged() {

    JPanel jPanel_parent = (JPanel) this.getParent();

    if (jPanel_parent != null) {
      jPanel_parent.firePropertyChange("CHANGED_INTERACTION_DATA", 0, 1);
    }

  }


  @Override
  public void setData(SELM_Interaction interaction) {

  }

  @Override
  public SELM_Interaction getData() {
    return null;
  }

  public void setMessage(String txt) {
    jLabel_message.setText(txt);
  }

  void modifyComponents() {
    
        
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_message = new javax.swing.JLabel();

        setName("NULL"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jLabel_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Interaction_NULL.class);
        jLabel_message.setText(resourceMap.getString("jLabel_message.text")); // NOI18N
        jLabel_message.setName("jLabel_message"); // NOI18N
        add(jLabel_message, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_message;
    // End of variables declaration//GEN-END:variables

  public String getRenderTag() {
    return atz3D_RENDER_TAG_INTERACTION_ANNOTATION;  /* indicate this is annotation */
  }

  public void renderToModel3D(Atz3D_Model model3D) {

  }

}
