package org.atzberger.application.selm_builder;

import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * Panel for editing this data type.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Integrator_Velocity_Verlet_Periodic_Lag extends JPanel_Integrator {

  application_SharedData applSharedData = null;

  TableModelListener localFireTableModelListener = null;

    /** Creates new form JPanel_Editor_Test1 */
    public JPanel_Integrator_Velocity_Verlet_Periodic_Lag() {
      initComponents();
    }

    public JPanel_Integrator_Velocity_Verlet_Periodic_Lag(application_SharedData applSharedData_in) {
      applSharedData = applSharedData_in;
      initComponents();

      /* add listener to the jTable_Eulerian for any changes there */
      localFireTableModelListener = new TableModelListener() {
        public void tableChanged(TableModelEvent e)  {
          jTable_Integrator_tableChanged(e);
        }
      };

      jTable_Integrator.getModel().addTableModelListener(localFireTableModelListener);


    }

    public void jTable_Integrator_tableChanged(TableModelEvent e)  {
      System.out.println("jTable_Integrator changed event" + e);

      fireIntegratorChanged();

    }

    public void fireIntegratorChanged() {

      JPanel jPanel_parent = (JPanel) this.getParent();

      if (jPanel_parent != null)
        jPanel_parent.firePropertyChange("CHANGED_INTEGRATOR_DATA", 0, 1);

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Integrator_LAMMPS_SHEAR1 = new javax.swing.JScrollPane();
        jTable_Integrator = new org.atzberger.mango.table.JTable_Properties1_Default();

        setMinimumSize(new java.awt.Dimension(400, 200));
        setName("Velocity_Verlet_Periodic_Lag"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));

        jScrollPane_Integrator_LAMMPS_SHEAR1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane_Integrator_LAMMPS_SHEAR1.setName("jScrollPane_Integrator_LAMMPS_SHEAR1"); // NOI18N

        jTable_Integrator.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        jTable_Integrator.setModel(new org.atzberger.application.selm_builder.TableModel_Integrator_Velocity_Verlet_Periodic_Lag(applSharedData.atz_UnitsRef));
        jTable_Integrator.setName("jTable_Integrator");
        jTable_Integrator.setRowSelectionAllowed(false);
        jScrollPane_Integrator_LAMMPS_SHEAR1.setViewportView(jTable_Integrator);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_Integrator_LAMMPS_SHEAR1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane_Integrator_LAMMPS_SHEAR1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane_Integrator_LAMMPS_SHEAR1;
    private javax.swing.JTable jTable_Integrator;
    // End of variables declaration//GEN-END:variables

  @Override
  public void setData(SELM_Integrator integrator) {
    turnOffActionListenerForEdits();
    ((TableModel_Integrator_Velocity_Verlet_Periodic_Lag)(jTable_Integrator.getModel())).setFromIntegratorData(integrator);
    turnOnActionListenerForEdits();
  }

  @Override
  public SELM_Integrator getData() {
    return ((TableModel_Integrator_Velocity_Verlet_Periodic_Lag)(jTable_Integrator.getModel())).getIntegratorDataFromModel();
  }


  public void turnOffActionListenerForEdits() {
    /* avoid firing event for this type of setting */
    jTable_Integrator.getModel().removeTableModelListener(localFireTableModelListener);

  }

  public void turnOnActionListenerForEdits() {
    /* restore firing of event for editing of table */
    jTable_Integrator.getModel().addTableModelListener(localFireTableModelListener);
  }


}
