package org.atzberger.mango.atz3d;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;

/**
 *
 * Interface panel to display the render view.  This includes an area that displays
 * a control panel of buttons and a region for rendering the model.
 *
 * @author Paul J. Atzberger
 *
 * @see <a href="http://www.atzberger.org">http://www.atzberger.org</a>
 */
public class JPanel_Model_View_Composite extends JPanel {

  /** Creates new form JPanel_Model_View_Composite */
  public JPanel_Model_View_Composite() {
    initComponents();
    
    LayoutManager lm = jPanel_Bottom_Containing_Render_Panel.getLayout();

    if (BoxLayout.class.isInstance(lm)) {
      //Component.CENTER_ALIGNMENT
    }
    
    //if (FlowLayout.class.isInstance(lm)) {
    //  FlowLayout flowLayout = (FlowLayout) lm;
    //  flowLayout.setAlignment(FlowLayout.CENTER);
    //}

  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Model_View_Controls = new javax.swing.ButtonGroup();
        jPopupMenu_Render_Panel = new javax.swing.JPopupMenu();
        jMenuItem_Rotation_Mode = new javax.swing.JMenuItem();
        jMenuItem_Slide_Mode = new javax.swing.JMenuItem();
        jMenuItem_Zoom_Mode = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPopup_Reset_Camera_View = new javax.swing.JMenuItem();
        jSplitPane_ControlPts_Render_and_Toolbar = new javax.swing.JSplitPane();
        jPanel_For_Toolbar_ControlPts_Top = new javax.swing.JPanel();
        jToolBar_Navigation_Controls = new javax.swing.JToolBar();
        jToggleButton_Rotation_Mode = new javax.swing.JToggleButton();
        jToggleButton_Slide_Mode = new javax.swing.JToggleButton();
        jToggleButton_Zoom_Mode = new javax.swing.JToggleButton();
        jButton_Reset_Camera_View = new javax.swing.JButton();
        jPanel_Bottom_Containing_Render_Panel = new javax.swing.JPanel();
        jPanel_Model_View_RenderPanel = new org.atzberger.mango.atz3d.JPanel_Model_View_RenderPanel();

        jPopupMenu_Render_Panel.setMinimumSize(new java.awt.Dimension(100, 50));
        jPopupMenu_Render_Panel.setName("jPopupMenu_Render_Panel"); // NOI18N
        jPopupMenu_Render_Panel.setPreferredSize(new java.awt.Dimension(179, 100));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.atzberger.application.selm_builder.application_Main.class).getContext().getResourceMap(JPanel_Model_View_Composite.class);
        jMenuItem_Rotation_Mode.setText(resourceMap.getString("jMenuItem_Rotation_Mode.text")); // NOI18N
        jMenuItem_Rotation_Mode.setName("jMenuItem_Rotation_Mode"); // NOI18N
        jMenuItem_Rotation_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Rotation_ModeActionPerformed(evt);
            }
        });
        jPopupMenu_Render_Panel.add(jMenuItem_Rotation_Mode);

        jMenuItem_Slide_Mode.setText(resourceMap.getString("jMenuItem_Slide_Mode.text")); // NOI18N
        jMenuItem_Slide_Mode.setName("jMenuItem_Slide_Mode"); // NOI18N
        jMenuItem_Slide_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Slide_ModeActionPerformed(evt);
            }
        });
        jPopupMenu_Render_Panel.add(jMenuItem_Slide_Mode);

        jMenuItem_Zoom_Mode.setText(resourceMap.getString("jMenuItem_Zoom_Mode.text")); // NOI18N
        jMenuItem_Zoom_Mode.setName("jMenuItem_Zoom_Mode"); // NOI18N
        jMenuItem_Zoom_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Zoom_ModeActionPerformed(evt);
            }
        });
        jPopupMenu_Render_Panel.add(jMenuItem_Zoom_Mode);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jPopupMenu_Render_Panel.add(jSeparator1);

        jMenuItemPopup_Reset_Camera_View.setText(resourceMap.getString("jMenuItemPopup_Reset_Camera_View.text")); // NOI18N
        jMenuItemPopup_Reset_Camera_View.setActionCommand(resourceMap.getString("jMenuItemPopup_Reset_Camera_View.actionCommand")); // NOI18N
        jMenuItemPopup_Reset_Camera_View.setName("jMenuItemPopup_Reset_Camera_View"); // NOI18N
        jMenuItemPopup_Reset_Camera_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPopup_Reset_Camera_ViewActionPerformed(evt);
            }
        });
        jPopupMenu_Render_Panel.add(jMenuItemPopup_Reset_Camera_View);

        setName("RenderView"); // NOI18N
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane_ControlPts_Render_and_Toolbar.setDividerLocation(33);
        jSplitPane_ControlPts_Render_and_Toolbar.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane_ControlPts_Render_and_Toolbar.setName("jSplitPane_ControlPts_Render_and_Toolbar"); // NOI18N

        jPanel_For_Toolbar_ControlPts_Top.setMinimumSize(new java.awt.Dimension(206, 33));
        jPanel_For_Toolbar_ControlPts_Top.setName("jPanel_For_Toolbar_ControlPts_Top"); // NOI18N
        jPanel_For_Toolbar_ControlPts_Top.setLayout(new javax.swing.BoxLayout(jPanel_For_Toolbar_ControlPts_Top, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar_Navigation_Controls.setRollover(true);
        jToolBar_Navigation_Controls.setName("jToolBar_Navigation_Controls"); // NOI18N

        buttonGroup_Model_View_Controls.add(jToggleButton_Rotation_Mode);
        jToggleButton_Rotation_Mode.setIcon(resourceMap.getIcon("jToggleButton_Rotation_Mode.icon")); // NOI18N
        jToggleButton_Rotation_Mode.setToolTipText(resourceMap.getString("jToggleButton_Rotation_Mode.toolTipText")); // NOI18N
        jToggleButton_Rotation_Mode.setActionCommand(resourceMap.getString("jToggleButton_Rotation_Mode.actionCommand")); // NOI18N
        jToggleButton_Rotation_Mode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton_Rotation_Mode.setFocusable(false);
        jToggleButton_Rotation_Mode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton_Rotation_Mode.setMaximumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Rotation_Mode.setMinimumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Rotation_Mode.setName("jToggleButton_Rotation_Mode"); // NOI18N
        jToggleButton_Rotation_Mode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton_Rotation_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Rotation_ModeActionPerformed(evt);
            }
        });
        jToolBar_Navigation_Controls.add(jToggleButton_Rotation_Mode);

        buttonGroup_Model_View_Controls.add(jToggleButton_Slide_Mode);
        jToggleButton_Slide_Mode.setIcon(resourceMap.getIcon("jToggleButton_Slide_Mode.icon")); // NOI18N
        jToggleButton_Slide_Mode.setToolTipText(resourceMap.getString("jToggleButton_Slide_Mode.toolTipText")); // NOI18N
        jToggleButton_Slide_Mode.setActionCommand(resourceMap.getString("jToggleButton_Slide_Mode.actionCommand")); // NOI18N
        jToggleButton_Slide_Mode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton_Slide_Mode.setMaximumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Slide_Mode.setMinimumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Slide_Mode.setName("jToggleButton_Slide_Mode"); // NOI18N
        jToggleButton_Slide_Mode.setPreferredSize(new java.awt.Dimension(32, 32));
        jToggleButton_Slide_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Slide_ModeActionPerformed(evt);
            }
        });
        jToolBar_Navigation_Controls.add(jToggleButton_Slide_Mode);

        buttonGroup_Model_View_Controls.add(jToggleButton_Zoom_Mode);
        jToggleButton_Zoom_Mode.setIcon(resourceMap.getIcon("jToggleButton_Zoom_Mode.icon")); // NOI18N
        jToggleButton_Zoom_Mode.setToolTipText(resourceMap.getString("jToggleButton_Zoom_Mode.toolTipText")); // NOI18N
        jToggleButton_Zoom_Mode.setActionCommand(resourceMap.getString("jToggleButton_Zoom_Mode.actionCommand")); // NOI18N
        jToggleButton_Zoom_Mode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton_Zoom_Mode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton_Zoom_Mode.setMaximumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Zoom_Mode.setMinimumSize(new java.awt.Dimension(32, 32));
        jToggleButton_Zoom_Mode.setName("jToggleButton_Zoom_Mode"); // NOI18N
        jToggleButton_Zoom_Mode.setPreferredSize(new java.awt.Dimension(32, 32));
        jToggleButton_Zoom_Mode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton_Zoom_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Zoom_ModeActionPerformed(evt);
            }
        });
        jToolBar_Navigation_Controls.add(jToggleButton_Zoom_Mode);

        jButton_Reset_Camera_View.setIcon(resourceMap.getIcon("jButton_Reset_Camera_View.icon")); // NOI18N
        jButton_Reset_Camera_View.setToolTipText(resourceMap.getString("jButton_Reset_Camera_View.toolTipText")); // NOI18N
        jButton_Reset_Camera_View.setActionCommand(resourceMap.getString("jButton_Reset_Camera_View.actionCommand")); // NOI18N
        jButton_Reset_Camera_View.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Reset_Camera_View.setContentAreaFilled(false);
        jButton_Reset_Camera_View.setFocusable(false);
        jButton_Reset_Camera_View.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Reset_Camera_View.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton_Reset_Camera_View.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton_Reset_Camera_View.setName("jButton_Reset_Camera_View"); // NOI18N
        jButton_Reset_Camera_View.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton_Reset_Camera_View.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_Reset_Camera_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Reset_Camera_ViewActionPerformed(evt);
            }
        });
        jToolBar_Navigation_Controls.add(jButton_Reset_Camera_View);

        jPanel_For_Toolbar_ControlPts_Top.add(jToolBar_Navigation_Controls);

        jSplitPane_ControlPts_Render_and_Toolbar.setLeftComponent(jPanel_For_Toolbar_ControlPts_Top);

        jPanel_Bottom_Containing_Render_Panel.setName("jPanel_Bottom_Containing_Render_Panel"); // NOI18N
        jPanel_Bottom_Containing_Render_Panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel_Bottom_Containing_Render_PanelComponentResized(evt);
            }
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel_Bottom_Containing_Render_PanelComponentMoved(evt);
            }
        });
        jPanel_Bottom_Containing_Render_Panel.setLayout(null);

        jPanel_Model_View_RenderPanel.setComponentPopupMenu(jPopupMenu_Render_Panel);
        jPanel_Model_View_RenderPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        jPanel_Model_View_RenderPanel.setName("jPanel_Model_View_RenderPanel"); // NOI18N
        jPanel_Model_View_RenderPanel.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanel_Model_View_RenderPanelLayout = new javax.swing.GroupLayout(jPanel_Model_View_RenderPanel);
        jPanel_Model_View_RenderPanel.setLayout(jPanel_Model_View_RenderPanelLayout);
        jPanel_Model_View_RenderPanelLayout.setHorizontalGroup(
            jPanel_Model_View_RenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel_Model_View_RenderPanelLayout.setVerticalGroup(
            jPanel_Model_View_RenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        jPanel_Bottom_Containing_Render_Panel.add(jPanel_Model_View_RenderPanel);
        jPanel_Model_View_RenderPanel.setBounds(0, 0, 398, 256);

        jSplitPane_ControlPts_Render_and_Toolbar.setRightComponent(jPanel_Bottom_Containing_Render_Panel);

        add(jSplitPane_ControlPts_Render_and_Toolbar);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton_Rotation_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Rotation_ModeActionPerformed
      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)jPanel_Model_View_RenderPanel;

      if ("Navigation_set".equals(evt.getActionCommand())) {
        renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Navigation); /* replace with constants */
      }
    }//GEN-LAST:event_jToggleButton_Rotation_ModeActionPerformed

    private void jButton_Reset_Camera_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Reset_Camera_ViewActionPerformed

      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)jPanel_Model_View_RenderPanel;

      if ("Reset_View_pressed".equals(evt.getActionCommand())) {
        renderControlPts.resetCameraView();

        /* also select the rotation mode as default */
        renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Navigation); /* replace with constants */
        buttonGroup_Model_View_Controls.setSelected(jToggleButton_Rotation_Mode.getModel(), true);

        renderControlPts.repaint();

        //jButton_ControlPts_Reset_View.setSelected(false); /* avoid having this selected */
      }
}//GEN-LAST:event_jButton_Reset_Camera_ViewActionPerformed

    private void jToggleButton_Slide_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Slide_ModeActionPerformed

      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)jPanel_Model_View_RenderPanel;

      if ("Move_set".equals(evt.getActionCommand())) {
        renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Move); /* replace with constants */
      }

    }//GEN-LAST:event_jToggleButton_Slide_ModeActionPerformed

    private void jPanel_Bottom_Containing_Render_PanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_Bottom_Containing_Render_PanelComponentResized
      
      Dimension sizeContainer    = jPanel_Bottom_Containing_Render_Panel.getSize();
      Dimension sizeContainerAdj = new Dimension();
      
      sizeContainerAdj.width  = (int) java.lang.Math.round(1.0*sizeContainer.width);
      sizeContainerAdj.height = (int) java.lang.Math.round(1.0*sizeContainer.height);

      jPanel_Model_View_RenderPanel.setSize(sizeContainerAdj);

      Dimension sizeRenderPort = jPanel_Model_View_RenderPanel.getSize();

      int xx = (sizeContainer.width/2) - (sizeRenderPort.width/2);
      int yy = (sizeContainer.height/2) - (sizeRenderPort.height/2);
      jPanel_Model_View_RenderPanel.setLocation(xx, yy);
      
      repaint();
      
    }//GEN-LAST:event_jPanel_Bottom_Containing_Render_PanelComponentResized

    private void jToggleButton_Zoom_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Zoom_ModeActionPerformed
      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)jPanel_Model_View_RenderPanel;

      if ("Zoom_set".equals(evt.getActionCommand())) {
        renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Zoom); /* replace with constants */
      }
    }//GEN-LAST:event_jToggleButton_Zoom_ModeActionPerformed

    private void jMenuItemPopup_Reset_Camera_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPopup_Reset_Camera_ViewActionPerformed

      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)this.jPanel_Model_View_RenderPanel;

      if ("Reset_View_pressed".equals(evt.getActionCommand())) {
        renderControlPts.resetCameraView();

        renderControlPts.repaint();
      }
}//GEN-LAST:event_jMenuItemPopup_Reset_Camera_ViewActionPerformed

    private void jMenuItem_Rotation_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Rotation_ModeActionPerformed
      
      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)this.jPanel_Model_View_RenderPanel;
      
      renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Navigation); /* replace with constants */
      buttonGroup_Model_View_Controls.setSelected(jToggleButton_Rotation_Mode.getModel(), true);
    
    }//GEN-LAST:event_jMenuItem_Rotation_ModeActionPerformed

    private void jMenuItem_Slide_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Slide_ModeActionPerformed
      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)this.jPanel_Model_View_RenderPanel;

      renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Move); /* replace with constants */
      buttonGroup_Model_View_Controls.setSelected(this.jToggleButton_Slide_Mode.getModel(), true);
    }//GEN-LAST:event_jMenuItem_Slide_ModeActionPerformed

    private void jMenuItem_Zoom_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Zoom_ModeActionPerformed
      JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel)this.jPanel_Model_View_RenderPanel;

      renderControlPts.setInterfaceMode(renderControlPts.interfaceMode_Zoom); /* replace with constants */
      buttonGroup_Model_View_Controls.setSelected(this.jToggleButton_Zoom_Mode.getModel(), true);
    }//GEN-LAST:event_jMenuItem_Zoom_ModeActionPerformed

    private void jPanel_Bottom_Containing_Render_PanelComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_Bottom_Containing_Render_PanelComponentMoved
      // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_Bottom_Containing_Render_PanelComponentMoved

    public JPanel_Model_View_RenderPanel getJPanel_Model_View_RenderPanel() {
      return (JPanel_Model_View_RenderPanel)jPanel_Model_View_RenderPanel;
    }


    public ButtonGroup getButtonGroup_Model_View_Controls() {
      return buttonGroup_Model_View_Controls;
    }


  public void setRenderBackgroundColors(Color bk1, Color bk2) {
    JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel) jPanel_Model_View_RenderPanel;

    if (renderControlPts != null) {
      renderControlPts.setRenderBackgroundColors(bk1, bk2);
    }

  }
  
  public void setRenderAxisInfo(boolean flagVisible, String[] axisLabels_in, Color axisColor_in, Color axisLabelColor_in) {
    JPanel_Model_View_RenderPanel renderControlPts = (JPanel_Model_View_RenderPanel) jPanel_Model_View_RenderPanel;

    if (renderControlPts != null) {
      renderControlPts.setAxisInfo(flagVisible, axisLabels_in, axisColor_in, axisLabelColor_in);

      renderControlPts.repaint();
    }

  }

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Model_View_Controls;
    private javax.swing.JButton jButton_Reset_Camera_View;
    private javax.swing.JMenuItem jMenuItemPopup_Reset_Camera_View;
    private javax.swing.JMenuItem jMenuItem_Rotation_Mode;
    private javax.swing.JMenuItem jMenuItem_Slide_Mode;
    private javax.swing.JMenuItem jMenuItem_Zoom_Mode;
    private javax.swing.JPanel jPanel_Bottom_Containing_Render_Panel;
    private javax.swing.JPanel jPanel_For_Toolbar_ControlPts_Top;
    private javax.swing.JPanel jPanel_Model_View_RenderPanel;
    private javax.swing.JPopupMenu jPopupMenu_Render_Panel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane_ControlPts_Render_and_Toolbar;
    private javax.swing.JToggleButton jToggleButton_Rotation_Mode;
    private javax.swing.JToggleButton jToggleButton_Slide_Mode;
    private javax.swing.JToggleButton jToggleButton_Zoom_Mode;
    private javax.swing.JToolBar jToolBar_Navigation_Controls;
    // End of variables declaration//GEN-END:variables

}
